/** Batch 5 translations for zizhitongjian ch.049 (s0406–s0423, 18 entries) */
/** Translator: Garrett M. Petersen (2026); Model: Composer */
export const batch5 = [
  { zh: "賊由是敗散。", literal: "The rebels thereby were defeated and scattered.", idiomatic: "The rebels were thereby defeated and scattered." },
  { zh: "詡乃占相地勢，築營壁百八十所，招還流亡，假賑貧民，開通水運。", literal: "Xu thereupon surveyed and assessed the terrain, built one hundred eighty fortified camps, summoned back the displaced, lent grain to relieve the poor, and opened water transport.", idiomatic: "Xu thereupon surveyed the terrain, built one hundred eighty fortified camps, summoned back refugees, lent grain to relieve the poor, and opened water transport." },
  { zh: "詡始到郡，谷石千，鹽石八千，見戶萬三千；", literal: "When Xu first arrived at the commandery, grain was a thousand per picul, salt eight thousand per picul, and registered households thirteen thousand;", idiomatic: "When Xu first arrived at the commandery, grain cost a thousand cash per picul, salt eight thousand per picul, and registered households numbered thirteen thousand;" },
  { zh: "視事三年，米石八十，鹽石四百，民增至四萬餘戶，人足家給，一郡遂安。", literal: "After three years in office, rice was eighty per picul, salt four hundred per picul, the people increased to more than forty thousand households, people had enough and households were provided for, and the whole commandery was then at peace.", idiomatic: "After three years in office, rice cost eighty cash per picul and salt four hundred per picul; the population increased to more than forty thousand households, people had enough and households were provided for, and the whole commandery was at peace." },
  { zh: "十一月，庚申，郡國十地震。", literal: "In the eleventh month, on gengshen day, ten commanderies and kingdoms had earthquakes.", idiomatic: "In the eleventh month, on gengshen day, ten commanderies and kingdoms had earthquakes." },
  { zh: "十二月，武陵澧中蠻反，州郡討平之。", literal: "In the twelfth month, the Lízhōng barbarians of Wuling rebelled; the province and commanderies subdued them.", idiomatic: "In the twelfth month the Lízhōng barbarians of Wuling rebelled; the province and commanderies subdued them." },
  { zh: "己酉，司徒夏勤罷，庚戌，以司空劉愷為司徒，光祿勳袁敞為司空。", literal: "On jiyou day, Grand Tutor Xia Qin was dismissed; on gengxu day, Minister of Works Liu Kai was made Grand Tutor, and Household Minister Yuan Chang was made Minister of Works.", idiomatic: "On jiyou day Grand Tutor Xia Qin was dismissed; on gengxu day Minister of Works Liu Kai was made Grand Tutor, and Household Minister Yuan Chang was made Minister of Works." },
  { zh: "敞，安之子也。", literal: "Chang was the son of An.", idiomatic: "Chang was the son of Yuan An." },
  { zh: "前虎賁中郎將鄧弘卒。", literal: "Former Colonel of the Rapid Horses in the Tiger Guard Deng Hong died.", idiomatic: "Former Colonel of the Rapid Horses in the Tiger Guard Deng Hong died." },
  { zh: "弘性儉素，治歐陽《尚書》，授帝禁中。", literal: "Hong's nature was frugal and plain; he studied Ouyang's Documents and instructed the Emperor within the inner palace.", idiomatic: "Hong was frugal and plain by nature; he studied Ouyang's Documents and instructed the Emperor within the inner palace." },
  { zh: "有司奏贈弘驃騎將軍，位特進，封西平侯。", literal: "The responsible offices memorialized to posthumously grant Hong General of the Agile Cavalry, position as Specialist-in-Chief, and enfeoffment as Marquis of Xiping.", idiomatic: "The responsible offices memorialized to posthumously grant Hong the title General of the Agile Cavalry, position as Specialist-in-Chief, and enfeoffment as Marquis of Xiping." },
  { zh: "太后追弘雅意，不加贈位、衣服，但賜錢千萬，布萬匹；", literal: "The empress dowager, recalling Hong's refined intent, did not add posthumous rank or robes, but only bestowed ten million cash and ten thousand bolts of cloth;", idiomatic: "The empress dowager, recalling Hong's refined simplicity, did not grant posthumous rank or burial robes, but only bestowed ten million cash and ten thousand bolts of cloth;" },
  { zh: "兄騭等復辭不受。", literal: "his elder brother Zhi and others again declined and would not accept.", idiomatic: "His elder brother Zhi and others again declined and would not accept." },
  { zh: "詔封弘子廣德為西平侯。", literal: "An edict enfeoffed Hong's son Guangde as Marquis of Xiping.", idiomatic: "An edict enfeoffed Hong's son Guangde as Marquis of Xiping." },
  { zh: "將葬，有司復奏發五營輕車騎士，禮儀如霍光故事。", literal: "When about to bury him, the responsible offices again memorialized to dispatch light chariot and horse cavalry from the five camps, the rites and ceremony following Huo Guang's precedent.", idiomatic: "When he was about to be buried, the responsible offices again memorialized to dispatch light chariot and horse cavalry from the five camps, with rites and ceremony following Huo Guang's precedent." },
  { zh: "太后皆不聽，但白蓋雙騎，門生輓送。", literal: "The empress dowager would not approve any of it, allowing only white canopy and double riders, with his students drawing the bier in escort.", idiomatic: "The empress dowager would not approve any of it, allowing only a white canopy and two horsemen, with his students serving as pallbearers." },
  { zh: "後以帝師之重，分西平之都鄉，封廣德弟甫德為都鄉侯。", literal: "Later, in view of the weight of being the Emperor's teacher, the Capital Township of Xiping was separated out and Guangde's younger brother Fude was enfeoffed as Marquis of Duxiang.", idiomatic: "Later, in view of the weight of his office as the Emperor's teacher, the Capital Township of Xiping was separated out and Guangde's younger brother Fude was enfeoffed as Marquis of Duxiang." },
  { zh: "category:資治通鑑", literal: "—", idiomatic: "—" },
];
