/** Batch 6 translations for zizhitongjian ch.009 (s0539–s0546, 7 entries) */
/** Translator: Garrett M. Petersen (2026); Model: Composer 2.5 */
export const batch6 = [
  { zh: "九月，信擊虜豹，傳詣滎陽；", literal: "In the ninth month Xin struck, captured Bao, and sent him by relay to Xingyang;", idiomatic: "In the ninth month Han Xin attacked, captured Bao, and sent him under escort to Xingyang;" },
  { zh: "悉定魏地，置河東、上黨、太原郡。", literal: "He fully settled Wei territory and established Hedong, Shangdang, and Taiyuan commanderies.", idiomatic: "He fully pacified Wei territory and established Hedong, Shangdang, and Taiyuan commanderies." },
  { zh: "26漢之敗於彭城而西也，陳餘亦覺張耳不死，即背漢。", literal: "26 When Han was defeated at Pengcheng and retreated west, Chen Yu also realized Zhang Er was not dead and at once turned against Han.", idiomatic: "26 When Han was defeated at Pengcheng and retreated west, Chen Yu too realized Zhang Er was alive and at once rebelled against Han." },
  { zh: "韓信既定魏，使人請兵三萬人，願以北舉燕、趙，東擊齊，南絕楚糧道。", literal: "Han Xin, having already settled Wei, sent men to request thirty thousand troops, wishing to raise Yan and Zhao in the north, strike Qi in the east, and cut off Chu's grain routes in the south.", idiomatic: "After Han Xin had pacified Wei, he sent envoys requesting thirty thousand troops, offering to take Yan and Zhao in the north, strike Qi in the east, and cut off Chu's grain routes in the south." },
  { zh: "漢王許之，乃遣張耳與俱，引兵東，北擊趙、代。", literal: "The King of Han agreed and then sent Zhang Er to go with him; he led his troops east and attacked Zhao and Dai in the north.", idiomatic: "The King of Han agreed, sent Zhang Er to accompany him, led his army east, and attacked Zhao and Dai in the north." },
  { zh: "後九月，信破代兵，禽夏說於閼與。", literal: "In the intercalary ninth month Xin defeated the Dai army and captured Xia Yue at Yan Yu.", idiomatic: "In the intercalary ninth month Han Xin routed the Dai army and captured Xia Yue at Yan Yu." },
  { zh: "信之下魏破代，漢輒使人收其精兵詣滎陽以距楚。", literal: "Whenever Xin subdued Wei or defeated Dai, Han would promptly send men to gather his picked troops and bring them to Xingyang to resist Chu.", idiomatic: "Whenever Han Xin took Wei or defeated Dai, the King of Han would promptly send men to gather his elite troops to Xingyang to hold Chu at bay." },
];
