/** Batch 5 translations for zizhitongjian ch.028 (s0408–s0412, 5 entries) */
/** Translator: Garrett M. Petersen (2026); Model: Composer */
export const batch5 = [
  { zh: "八月，拜太常弋陽侯任千秋為奮武將軍以助之。", literal: "In the eighth month, Ren Qianqiu, Marquis of Yiyang and Grand Master of Ceremonies, was appointed General Who Displays Martial Might to assist him.", idiomatic: "In the eighth month Ren Qianqiu, Marquis of Yiyang and Grand Master of Ceremonies, was appointed General Who Displays Martial Might to assist him." },
  { zh: "冬，十月，兵畢至隴西，十一月，並進，羌虜大破，斬首數千級，餘皆走出塞。", literal: "In winter, the tenth month, the troops all arrived at Longxi; in the eleventh month they advanced together. The Qiang barbarians were greatly defeated; heads cut numbered several thousand; the remainder all fled out beyond the frontier passes.", idiomatic: "In winter, the tenth month, the troops all reached Longxi; in the eleventh month they advanced together. The Qiang were routed, several thousand heads were taken, and the rest all fled beyond the frontier." },
  { zh: "兵未決間，漢復發募士萬人，拜定襄太守韓安國為建威將軍，未進，聞羌破而還。", literal: "While the campaign was not yet decided, Han again raised and recruited ten thousand men, appointing Han Anguo, Administrator of Dingxiang, as General Who Establishes Might. He had not advanced when he heard the Qiang were broken and returned.", idiomatic: "While the campaign was still undecided, Han again recruited ten thousand men and appointed Han Anguo, Administrator of Dingxiang, as General Who Establishes Might. He had not advanced when he heard the Qiang were defeated and returned." },
  { zh: "詔罷吏士，頗留屯田，備要害處。", literal: "An edict dismissed officers and soldiers, but many were left for garrison-farming to guard strategic points.", idiomatic: "An edict dismissed the officers and soldiers, but many were left to garrison-farm and guard strategic points." },
  { zh: "category:資治通鑑", literal: "category: Comprehensive Mirror in Aid of Governance", idiomatic: "category: Comprehensive Mirror in Aid of Governance" },
];
