/** Batch 7 translations for zizhitongjian ch.004 */
/** Translator: Garrett M. Petersen (2026); Model: Composer 2.5 */
export const batch7 = [
  { zh: "此皆平原四達膏腴之地。", literal: "These are all level plains open on four sides, rich and fertile lands.", idiomatic: "These are all level plains with roads in every direction, rich and fertile country." },
  { zh: "如此，則天下之國莫強於齊、魏矣。", literal: "If so, then among states under Heaven none will be stronger than Qi and Wei.", idiomatic: "If things go thus, then among the states of the world none will be stronger than Qi and Wei." },
  { zh: "臣為王慮，莫若善楚。", literal: "Your servant has considered for Your Majesty: nothing is better than treating Chu well.", idiomatic: "I have weighed matters for Your Majesty: you had best befriend Chu." },
  { zh: "秦、楚合而為一以臨韓，韓必斂手而朝；", literal: "If Qin and Chu unite as one to face Han, Han will surely fold its hands and pay court;", idiomatic: "If Qin and Chu unite and press Han, Han will surely fold its hands and submit;" },
  { zh: "王施以東山之險，帶以曲河之利，韓必為關內之侯。", literal: "Your Majesty deploying the danger of the eastern hills, girding with the advantage of the winding rivers, Han will surely become a marquis within the pass.", idiomatic: "Deploy the heights of the eastern hills and bind them with the advantage of the winding rivers, and Han will surely become a marquis of the inner domain." },
  { zh: "若是而王以十萬戍鄭，梁氏寒心，許、鄢陵嬰城而上蔡、召陵不往來也。", literal: "If so, and Your Majesty garrisons Zheng with a hundred thousand, the house of Liang will lose heart; Xu and Yanling will wall their cities; and Shangcai and Shaoling will have no coming and going.", idiomatic: "Then, if Your Majesty stations a hundred thousand at Zheng, Wei will lose heart; Xu and Yanling will shut their walls; Shangcai and Shaoling will cease their traffic." },
  { zh: "如此，魏亦關內侯矣。", literal: "If so, Wei too will be a marquis within the pass.", idiomatic: "If so, Wei too will be a marquis of the inner domain." },
  { zh: "王壹善楚而關內兩萬乘之主注地於齊，齊右壤可拱手而取也。", literal: "If Your Majesty befriends Chu in one stroke and the two lords of ten thousand chariots within the pass pour territory toward Qi, Qi's right lands can be taken with folded hands.", idiomatic: "Befriend Chu outright, and when the two ten-thousand-chariot lords within the pass turn their lands toward Qi, you can take Qi's right flank with folded hands." },
  { zh: "王之地一經兩海，要約天下，是燕、趙無齊、楚，齊、楚無燕、趙也。", literal: "Your Majesty's lands running through both seas, binding the world under key terms—Yan and Zhao will lack Qi and Chu, Qi and Chu will lack Yan and Zhao.", idiomatic: "Your lands will span both seas and bind the world by strategic holds; Yan and Zhao will lack Qi and Chu, and Qi and Chu will lack Yan and Zhao." },
  { zh: "然後危動燕、趙，直搖齊、楚，此四國者不待痛而服矣。", literal: "Then threaten and stir Yan and Zhao, shake Qi and Chu directly—these four states will submit without being wounded.", idiomatic: "Then alarm Yan and Zhao and shake Qi and Chu directly—these four states will yield without your needing to wound them." },
  { zh: "」王從之，止武安君而謝韓、魏，使黃歇歸，約親於楚。", literal: "” The king followed this, stopped the Lord of Wu'an and apologized to Han and Wei, sent Huang Xie home, and pledged kinship with Chu.", idiomatic: "” The king accepted this, held back the Lord of Wu'an and made apology to Han and Wei, sent Huang Xie home, and pledged alliance with Chu." },
  { zh: "<divclass=\"references-small\"><references/></div>", literal: "<divclass=\"references-small\"><references/></div>", idiomatic: "<divclass=\"references-small\"><references/></div>" },
  { zh: "周", literal: "Zhou", idiomatic: "Zhou" },
];
