/** Batch 5 translations for zizhitongjian ch.047 (s0411–s0423, 13 entries) */
/** Translator: Garrett M. Petersen (2026); Model: Composer */
export const batch5 = [
  { zh: "今朔漠既定，宜令南單于反其北庭，並領降眾，無緣復更立於除鞬以增國費。", literal: "Now the northern desert is settled; it is fitting to order the Southern Chanyu to return to his northern court and jointly lead the surrendered masses—there is no occasion to again establish Yu Chujian and increase state expense.", idiomatic: "Now that the northern desert is settled, the Southern Chanyu should be ordered to return to his northern court and take charge of all surrendered peoples as well; there is no reason to establish Yu Chujian anew and increase state expense." },
  { zh: "」事奏，未以時定。", literal: "\" When the memorial was submitted, it was not decided in time.", idiomatic: "When the memorial was submitted, it was not decided in time." },
  { zh: "安懼憲計遂行，乃獨上封事曰：「南單于屯先父舉眾歸德，自蒙恩以來四十餘年，三帝積累以遺陛下，陛下深宜遵述先志，成就其業，況屯首唱大謀，空盡北虜，輟而弗圖，更立新降；", literal: "An feared Xian's plan would be carried out and thereupon alone submitted a sealed memorial, saying: \"The Southern Chanyu Tun—his father formerly led the masses to submit in virtue; since receiving grace more than forty years have passed; three emperors accumulated and bequeathed to Your Majesty; Your Majesty should deeply follow and trace the former intent and complete his enterprise; moreover Tun was first to propose the great plan and utterly exhausted the northern barbarians—then to stop and not pursue it while instead establishing the newly surrendered;", idiomatic: "An feared Xian's plan would be carried out and thereupon submitted a sealed memorial alone, saying, \"The Southern Chanyu Tun—his father formerly led the masses to submit in allegiance; since receiving grace more than forty years have passed, and three emperors accumulated and bequeathed to Your Majesty—Your Majesty should deeply follow the former intent and complete his enterprise. Moreover Tun was first to propose the great plan and utterly exhausted the northern barbarians—then to stop and not pursue it while instead establishing the newly surrendered;" },
  { zh: "以一朝之計，違三世之規，失信於所養，建立於無功。", literal: "by a single court's scheme to violate three generations' rule, break faith with those fostered, and establish on those without merit.", idiomatic: "by a single court's scheme to violate three generations' policy, break faith with those you have fostered, and establish reward on those without merit." },
  { zh: "《論語》曰：『言忠信，行篤敬，雖蠻貊行焉。", literal: "The Analects says: \"Speak with loyalty and faith, act with earnest respect—even among barbarians one may go.", idiomatic: "The Analects says, \"Speak with loyalty and faith, act with earnest respect—even among barbarians one may go.\"" },
  { zh: "』今若失信於一屯，則百蠻不敢復保誓矣。", literal: "\" Now if faith is broken with this one Tun, then the hundred barbarians will not dare again to keep their oaths.", idiomatic: "Now if faith is broken with this one Tun, then the hundred barbarians will not dare again to keep their oaths." },
  { zh: "又，烏桓、鮮卑新殺北單于，凡人之情，鹹畏仇讎，今立其弟，則二虜懷怨。", literal: "Moreover, the Wuhuan and Xianbei have newly killed the Northern Chanyu; the common disposition of men—all fear their foes and enemies; now to establish his younger brother will make the two barbarians harbor resentment.", idiomatic: "Moreover, the Wuhuan and Xianbei have newly killed the Northern Chanyu; it is human nature that all fear their foes and enemies—now to establish his younger brother will make the two barbarians harbor resentment." },
  { zh: "且漢故事，供給南單于，費直歲一億九十餘萬，西域歲七千四百八十萬；", literal: "Moreover, Han precedent supplies the Southern Chanyu at a cost of more than one hundred nine million per year; the Western Regions seven thousand four hundred eighty thousand per year;", idiomatic: "Moreover, by Han precedent the supply for the Southern Chanyu costs more than one hundred nine million cash per year, and for the Western Regions seven thousand four hundred eighty thousand per year;" },
  { zh: "今北庭彌遠，其費過倍，是乃空盡天下而非建策之要地。", literal: "now the northern court is ever farther—its expense more than doubled; this is to empty all under Heaven, not the essential point of founding policy.", idiomatic: "now the northern court is ever farther and the expense more than doubled—this would empty all under Heaven, not the essential point of founding policy.\"" },
  { zh: "」詔下其議，安又與憲更相難折。", literal: "\" An edict sent down their deliberation; An again with Xian repeatedly rebutted and debated.", idiomatic: "An edict sent down their deliberation; An again debated sharply back and forth with Xian." },
  { zh: "憲險急負執，言辭驕訐，至詆毀安，稱光武誅韓歆、戴涉故事，安終不移；", literal: "Xian was dangerous, hasty, and stubbornly obstinate; his words proud and deceitful, even to slandering An and citing Guangwu's execution of Han Xin and Dai She as precedent—An in the end did not shift;", idiomatic: "Xian was dangerous, hasty, and stubbornly obstinate; his words were proud and deceitful, even to slandering An and citing Guangwu's execution of Han Xin and Dai She as precedent—An in the end did not yield;" },
  { zh: "然上竟從憲策。", literal: "yet the Emperor in the end followed Xian's plan.", idiomatic: "yet the Emperor in the end followed Xian's plan." },
  { zh: "category:資治通鑑", literal: "—", idiomatic: "—" },
];
