/** Batch 6 translations for zizhitongjian ch.037 (s0502–s0508, 7 entries) */
/** Translator: Garrett M. Petersen (2026); Model: Composer */
export const batch6 = [
  { zh: "益州蠻夷愁擾，盡反，復殺益州大尹程隆。", literal: "The barbarian Yi of Yizhou, aggrieved and disturbed, all rebelled and again killed Grand Administrator of Yizhou Cheng Long.", idiomatic: "The barbarian Yi of Yizhou, aggrieved and disturbed, all rebelled and again killed Grand Administrator of Yizhou Cheng Long." },
  { zh: "莽遣平蠻將軍馮茂發巴、蜀、犍為吏士，賦斂取足於民，以擊之。", literal: "Mang dispatched Pacification-of-Barbarians General Feng Mao to mobilize clerks and soldiers from Ba, Shu, and Qianwei, levying and extracting sufficiency from the people, to strike them.", idiomatic: "Wang Mang sent Pacification-of-Barbarians General Feng Mao to raise troops from Ba, Shu, and Qianwei, wringing the people until funds were sufficient, then marched to strike them." },
  { zh: "莽復申下金、銀、龜、貝之貨，頗增減其賈直，而罷大、小錢，改作貨布、貨泉二品並行。", literal: "Mang again promulgated the currencies of gold, silver, turtle [shells], and cowries, somewhat increasing or decreasing their set values, abolished large and small coins, and reformed them into Huo Bu and Huo Quan as two denominations circulating together.", idiomatic: "Wang Mang again promulgated gold, silver, turtle shells, and cowries, somewhat adjusting their set values, abolished large and small coins, and reformed currency into Huo Bu and Huo Quan as two denominations circulating together." },
  { zh: "又以大錢行久，罷之恐民挾不止，乃令民且獨行大錢；", literal: "Moreover, because the large coin had circulated long, he feared that abolishing it the people would not stop hoarding it; he therefore ordered the people for the time being to circulate the large coin alone;", idiomatic: "Moreover, because the large coin had circulated long, he feared that abolishing it would not stop the people from hoarding it; he therefore ordered the people for the time being to circulate the large coin alone;" },
  { zh: "盡六年，毋得復挾大錢矣。", literal: "After a full six years, they were no longer permitted to hoard large coins.", idiomatic: "After a full six years, they were no longer permitted to hoard large coins." },
  { zh: "每壹易錢，民用破業而大陷刑。", literal: "Each time the currency was changed, the common people lost their livelihoods and many fell deeply into criminal punishment.", idiomatic: "Each time the currency was changed, the common people lost their livelihoods and many fell deeply into criminal punishment." },
  { zh: "category:資治通鑑", literal: "—", idiomatic: "—" },
];
