/** Batch 6 translations for zizhitongjian ch.042 (s0511–s0529, 19 entries) */
/** Translator: Garrett M. Petersen (2026); Model: Composer */
export const batch6 = [
  { zh: "邛穀王任貴聞彭威信，數千里遣使迎降；", literal: "Qionggu King Ren Gui heard of Peng's prestige and trustworthiness and from several thousand li sent envoys to welcome and surrender;", idiomatic: "Qionggu King Ren Gui heard of Cen Peng's prestige and from several thousand li sent envoys to welcome and surrender;" },
  { zh: "會彭已被害，帝盡以任貴所獻賜彭妻子。", literal: "but Peng had already been killed; the Emperor gave all that Ren Gui had presented to Peng's wife and children.", idiomatic: "But Cen Peng had already been killed; the Emperor gave all that Ren Gui had presented to Cen Peng's wife and children." },
  { zh: "蜀人為立廟祠之。", literal: "The people of Shu built a temple and sacrificed to him.", idiomatic: "The people of Shu built a temple and sacrificed to him." },
  { zh: "10馬成等破河池，遂平武都。", literal: "10. Ma Cheng and others defeated Hechi and thereby pacified Wudu.", idiomatic: "10. Ma Cheng and others defeated Hechi and thereby pacified Wudu." },
  { zh: "先零諸種羌數萬人，屯聚寇鈔，拒浩亹隘。", literal: "Several tens of thousands of Xianliang and various Qiang tribes gathered to plunder and held the Hao'ai Pass.", idiomatic: "Several tens of thousands of Xianliang and various Qiang tribes gathered to plunder and held the Hao'ai Pass." },
  { zh: "成與馬援深入討擊，大破之，徙降羌置天水、隴西、扶風。", literal: "Cheng with Ma Yuan penetrated deep in pursuit and attack, routed them greatly, and relocated the submitted Qiang to Tianshui, Longxi, and Fufeng.", idiomatic: "Ma Cheng with Ma Yuan penetrated deep in pursuit, routed them completely, and relocated the submitted Qiang to Tianshui, Longxi, and Fufeng." },
  { zh: "是時，朝臣以金城破羌之西，塗遠多寇，議欲棄之。", literal: "At this time the court ministers, because west of Jincheng's Poqiang the road was long and bandits many, debated abandoning it.", idiomatic: "At this time the court ministers, because west of Jincheng's Poqiang the road was long and bandits were many, debated abandoning the region." },
  { zh: "馬援上言：「破羌以西，城多完牢，易可依固。", literal: "Ma Yuan memorialized: \"West of Poqiang, cities are mostly intact and strong and easy to rely on and hold firm.", idiomatic: "Ma Yuan memorialized, \"West of Poqiang, cities are mostly intact and strong and easy to hold.\"" },
  { zh: "其田土肥壤，灌溉流通。", literal: "Its fields and soil are fertile; irrigation flows through.", idiomatic: "Its fields and soil are fertile, and irrigation flows through." },
  { zh: "如令羌在湟中，則為害不休，不可棄也。", literal: "If the Qiang are allowed to remain in Huangzhong, harm will not cease—it cannot be abandoned.", idiomatic: "If the Qiang are allowed to remain in Huangzhong, harm will never cease—it cannot be abandoned.\"" },
  { zh: "」帝從之。", literal: "\" The Emperor followed it.", idiomatic: "The Emperor accepted his advice." },
  { zh: "民歸者三千餘口，援為置長吏，繕城郭，起塢候，開溝洫，勸以耕牧，郡中樂業。", literal: "People who returned numbered more than three thousand mouths; Yuan established chief officials, repaired walls and towers, raised walled watch-posts, opened irrigation ditches, urged farming and herding, and within the commandery all were glad in their occupations.", idiomatic: "More than three thousand people returned; Ma Yuan appointed chief officials, repaired walls and towers, raised walled watch-posts, opened irrigation ditches, urged farming and herding, and the commandery prospered in peace." },
  { zh: "又招撫塞外氏、羌，皆來降附，援奏復其侯王君長，帝悉從之。", literal: "He also recruited and pacified the Di and Qiang beyond the passes; all came to submit and attach themselves; Yuan memorialized to restore their marquis-kings and chieftains, and the Emperor accepted all.", idiomatic: "He also recruited and pacified the Di and Qiang beyond the passes; all came to submit; Ma Yuan memorialized to restore their marquis-kings and chieftains, and the Emperor accepted all." },
  { zh: "乃罷馬成軍。", literal: "He then dismissed Ma Cheng's army.", idiomatic: "He then dismissed Ma Cheng's army." },
  { zh: "11十二月，吳漢自夷陵將三萬人溯江而上，伐公孫述。", literal: "11. Twelfth month: Wu Han from Yiling led thirty thousand men up the Yangzi to attack Gongsun Shu.", idiomatic: "11. In the twelfth month, Wu Han from Yiling led thirty thousand men up the Yangzi to attack Gongsun Shu." },
  { zh: "12郭人及為并州牧，過京師，帝問以得失，人及曰：「選補眾職，當簡天下賢俊，不宜專用南陽人。", literal: "12. Guo Renji became Governor of Bingzhou; passing through the capital, the Emperor asked him about gains and losses; Renji said: \"In selecting and filling all posts one should choose the realm's worthy talent and not exclusively employ men of Nanyang.", idiomatic: "12. Guo Renji became Governor of Bingzhou; passing through the capital, the Emperor asked him about gains and losses; Renji said, \"In selecting and filling all posts one should choose the realm's worthy talent and not exclusively employ men of Nanyang.\"" },
  { zh: "」是時在位多鄉曲故舊，故人及言及之。", literal: "\" At this time those in office were mostly hometown acquaintances and old friends, so Renji's words touched on this.", idiomatic: "At this time those in office were mostly hometown acquaintances and old friends, so Renji's words touched on this." },
  { zh: "<divclass=\"references-small\"><references/></div>", literal: "<divclass=\"references-small\"><references/></div>", idiomatic: "<divclass=\"references-small\"><references/></div>" },
  { zh: "category:資治通鑑", literal: "—", idiomatic: "—" },
];
