/** Batch 6 translations for zizhitongjian ch.024 (s0512–s0525, 14 entries) */
/** Translator: Garrett M. Petersen (2026); Model: Composer 2.5 */
export const batch6 = [
  { zh: "是以漢世良吏，於是為盛，稱中興焉。", literal: "Thus in the Han age good officials were then at their flourishing, and it was called the Restoration.", idiomatic: "Thus in the Han age good officials flourished as never before, and the era was called the Restoration." },
  { zh: "----5匈奴壺衍鞮單于死，弟左賢王立為虛閭權渠單于，以右大將女為大閼氏，而黜前單于所幸顓渠閼氏。", literal: "----5 Chanyu Huyandi of the Xiongnu died; his younger brother the Left Wise King was established as Chanyu Xulüquanqu, took the Right Grand General's daughter as great yanzhi, and dismissed the former chanyu's favored Zhuanqu yanzhi.", idiomatic: "----5 Chanyu Huyandi of the Xiongnu died; his younger brother the Left Wise King became Chanyu Xulüquanqu, made the Right Grand General's daughter chief queen, and demoted the former chanyu's favored Zhuanqu." },
  { zh: "顓渠閼氏父左大且渠怨望。", literal: "Zhuanqu yanzhi's father, the Left Grand Daqu, bore resentment.", idiomatic: "Zhuanqu's father, the Left Grand Daqu, nursed a grudge." },
  { zh: "是時漢以匈奴不能為邊寇，罷塞外諸城以休百姓。", literal: "At this time Han, because the Xiongnu could not raid the borders, abolished the various cities beyond the passes to rest the common people.", idiomatic: "At this time Han, seeing the Xiongnu could not raid the borders, dismantled outpost cities beyond the passes to spare the people." },
  { zh: "單于聞之，喜，召貴人謀，欲與漢和親。", literal: "The chanyu heard it and was pleased; he summoned nobles to deliberate and wished to make peace kinship with Han.", idiomatic: "The chanyu rejoiced, summoned his nobles to counsel, and wished to seek peace kinship with Han." },
  { zh: "左大且渠心害其事，曰：「前漢使來，兵隨其後。", literal: "The Left Grand Daqu inwardly resented the affair and said: \"Previously when Han envoys came, troops followed behind them.", idiomatic: "The Left Grand Daqu inwardly opposed the plan and said, \"Previously when Han envoys came, troops followed behind them." },
  { zh: "今亦效漢發兵，先使使者入。", literal: "Now too imitate Han in raising troops—first send envoys in.", idiomatic: "Now imitate Han: raise troops and send envoys in first." },
  { zh: "」乃自請與呼盧訾王各將萬騎，南旁塞獵，相逢俱入。", literal: "\" Thereupon he himself requested that he and King Hulüze each lead ten thousand horsemen south to hunt beside the barrier, meet, and enter together.", idiomatic: "\" He then volunteered that he and King Hulüze each lead ten thousand horsemen south to hunt along the border, meet up, and enter together." },
  { zh: "行未到，會三騎亡降漢，言匈奴欲為寇。", literal: "Before they had gone, it happened that three riders fled and surrendered to Han, saying the Xiongnu wished to raid.", idiomatic: "Before they arrived, three riders defected to Han and reported that the Xiongnu intended to raid." },
  { zh: "於是天子詔發邊騎屯要害處，使大將軍軍監治眾等四人將五千騎，分三隊，出塞各數百里，捕得虜各數十人而還。", literal: "Thereupon the Son of Heaven ordered border cavalry to encamp at critical points and sent four army supervisors of the Grand General such as Zhi Zhong, each leading five thousand horsemen in three columns beyond the passes several hundred li each, capturing several tens of captives each and returning.", idiomatic: "Thereupon the emperor ordered border cavalry to garrison chokepoints and sent four Grand General's army supervisors including Zhi Zhong, each with five thousand horsemen in three columns beyond the passes for several hundred li each, capturing several tens of captives apiece before returning." },
  { zh: "時匈奴亡其三騎，不敢入，即引去。", literal: "At that time the Xiongnu, having lost those three riders, did not dare enter and at once withdrew.", idiomatic: "The Xiongnu, missing those three riders, did not dare enter and at once withdrew." },
  { zh: "是歲，匈奴饑，人民、畜產死者什六七，又發兩屯各萬騎以備漢。", literal: "That year the Xiongnu suffered famine; of the people and livestock six or seven tenths died, and they also raised two encampments of ten thousand horsemen each to guard against Han.", idiomatic: "That year famine struck the Xiongnu; six or seven tenths of the people and livestock perished, and they still posted two camps of ten thousand horsemen each against Han." },
  { zh: "其秋，匈奴前所得西嗕居左地者，其君長以下數千人皆驅畜產行，與甌脫戰，所殺傷甚眾，遂南降漢。", literal: "That autumn those the Xiongnu had earlier taken from the Western Ruo dwelling in the left zone—from chiefs downward, several thousand in all—all drove livestock on the march, fought Ouduo, killed and wounded very many, and thereupon went south to surrender to Han.", idiomatic: "That autumn several thousand western captives the Xiongnu had held in the left zone—from chiefs downward—drove their herds forth, fought their Ouduo guards, inflicted heavy casualties, and defected south to Han." },
  { zh: "----category:資治通鑑", literal: "----category: Zizhi Tongjian", idiomatic: "----category: Zizhi Tongjian" },
];
