import fs from 'node:fs';

const batch = new Map();

batch.set('s0302', { literal: `Xiong said, "I have already divined for you and obtained the man."`, idiomatic: `Bu Xiong said he had already identified the culprit by divination.` });
batch.set('s0303', { literal: `Have him go south on the road; there ought to be a man who comes asking whether the master of the fire has been found—then bind him."`, idiomatic: `He told the clerk to walk south until someone asked about the "fire's master," then seize him.` });
batch.set('s0304', { literal: `" The clerk acted as Xiong said; it was indeed a ploughman who said of himself that the grass was bad and hard to plough, therefore he burned it; suddenly wind rose and the fire spread far and near; in truth he did not know there was a man in the grass.`, idiomatic: `The man was a farmer who had torched stubble for clearing; a gust spread the blaze and he never knew someone lay hidden in the weeds.` });
batch.set('s0305', { literal: `Moreover a neighbor's son went far away; someone reported he had died; his parents wailed and donned mourning; Xiong divined for them that on the appointed day he ought to return, and at the term he indeed arrived.`, idiomatic: `When neighbors thought a boy dead abroad, Bu Xiong set a return date—and the youth walked home on that very day.` });
batch.set('s0306', { literal: `Prince Zhao Lun heard his name and summoned him.`, idiomatic: `Prince Sima Lun of Zhao summoned him to court.` });
batch.set('s0307', { literal: `Xiong said to the students, "Lun will not long survive—it is not worth answering."`, idiomatic: `Bu Xiong told his pupils Sima Lun was doomed and the summons was beneath their notice.` });
batch.set('s0308', { literal: `" Lun raged and sent troops to surround them in many layers.`, idiomatic: `Sima Lun ringed the school with soldiers.` });
batch.set('s0309', { literal: `Xiong then had the students put on his furs and run south; Lun's soldiers all rushed to seize them; Xiong secretly went out from the north and escaped.`, idiomatic: `He dressed disciples in his own robes as decoys while he slipped out the north side.` });
batch.set('s0310', { literal: `Later he was recruited by Prince Chengdu Ying; Ying had Xiong shoot the covered vessel—nothing was ever missed.`, idiomatic: `Sima Ying of Chengdu employed him for "cover-shoot" divination, and he never failed to name the hidden object.` });
batch.set('s0311', { literal: `Later Ying fled into the passes; the Duke of Pingchang, Mo, garrisoned Ye; because Xiong was Ying's partisan, he executed him.`, idiomatic: `When Sima Ying fled to Guanzhong and Sima Mo held Ye, Mo executed Bu Xiong as a partisan of the prince.` });
batch.set('s0312', { literal: `Du Buqian.`, idiomatic: `Du Buqian` });
batch.set('s0313', { literal: `Du Buqian was a man of Lujiang.`, idiomatic: `Du Buqian came from Lujiang commandery.` });
batch.set('s0314', { literal: `In youth he studied the Changes and divination with his maternal grandfather Guo Pu.`, idiomatic: `As a boy he learned the Zhouyi and yarrow lore under his grandfather Guo Pu.` });
batch.set('s0315', { literal: `Repeatedly there were verifications.`, idiomatic: `His readings proved true again and again.` });
batch.set('s0316', { literal: `Xi Chao of Gaoping, over twenty years of age, contracted a grave illness; they tried having him cast the yarrow.`, idiomatic: `Xi Chao of Gaoping, barely twenty, fell dangerously ill; his household asked Du Buqian to cast.` });
batch.set('s0317', { literal: `Buqian said, "According to the hexagram what you suffer will soon be removed.`, idiomatic: `Du Buqian said the lines showed the ailment lifting soon.` });
batch.set('s0318', { literal: `Yet you ought to go to a family surnamed Shang on the high ground thirty li northeast and seek the cockerel they raise, put it in a cage and place it under the east eaves; afterward on the ninth day, bingwu day, at the wu double-hour, there ought surely to be a hen that flies in and mates with it; when both have gone away—`, idiomatic: `He prescribed a ritual: fetch a rooster from a Shang family on a rise thirty li northeast, cage it under the east eaves, and on the ninth day at noon a hen would arrive to mate—` });
batch.set('s0319', { literal: `if so, within twenty days the illness will entirely be gone; moreover it is a sign of rest; the years will approach eighty, and rank will reach the utmost of human ministers.`, idiomatic: `if that happened, the sickness would vanish within twenty days, he would live toward eighty, and rise to the highest ministerial rank.` });
batch.set('s0320', { literal: `If only the hen departs and the cock remains, the illness will improve after one week, the years half of eighty, and name and rank likewise lost."`, idiomatic: `If the hen left while the cock stayed, he would mend after a week but lose half his years and his career prospects.` });
batch.set('s0321', { literal: `" Chao at the time was just emaciated and gravely ill, worried his life was at dawn and dusk; smiling he answered, "If it secures half of eighty, that is already more than enough.`, idiomatic: `Xi Chao, wasted and near death, laughed that half of eighty would be plenty.` });
batch.set('s0322', { literal: `One week's illness mended—what is worth calling a delay!"`, idiomatic: `A week's convalescence seemed a trifle.` });
batch.set('s0323', { literal: `" Yet he did not believe it.`, idiomatic: `Still he doubted the oracle.` });
batch.set('s0324', { literal: `Someone urged him to follow the words; he sought the cocks and indeed obtained them.`, idiomatic: `Friends pressed him to obey; he found the birds as directed.` });
batch.set('s0325', { literal: `On the bingwu day Chao lay under the south gallery watching; by the time the sun was low, indeed a hen flew into the cage, mated with the cock, and departed; the cock did not move.`, idiomatic: `At noon on bingwu he watched from the south loggia until a hen flew in, coupled, and flew off while the rooster stayed.` });
batch.set('s0326', { literal: `Chao sighed, "Though Guan and Guo were marvelous, how could they surpass this!"`, idiomatic: `Xi Chao marveled that even Guan Lu and Guo Pu could not match such precision.` });
batch.set('s0327', { literal: `" Chao's illness lasted a full year before he rose; at forty he died as Palace Secretary.`, idiomatic: `His illness lingered a year before he rose; he died at forty as a secretary at the palace bureau.` });
batch.set('s0328', { literal: `Afterward Buqian's divinations grew cruder and there were no more cases of this sort.`, idiomatic: `Later Du Buqian's casts grew rougher, and nothing so striking happened again.` });
batch.set('s0329', { literal: `Later he became adjutant to Huan Si's General Who Establishes Might.`, idiomatic: `He ended as staff officer to Huan Si, general who establishes might.` });
batch.set('s0330', { literal: `Yan Qing.`, idiomatic: `Yan Qing` });
batch.set('s0331', { literal: `Yan Qing was a man of Kuaiji.`, idiomatic: `Yan Qing was a native of Kuaiji.` });
batch.set('s0332', { literal: `He was skilled at divination by yarrow.`, idiomatic: `He excelled at yarrow divination.` });
batch.set('s0333', { literal: `Fellow townsman Wei Xu wished to go east for a time; in famine years there was much banditry; he ordered Qing to divine it.`, idiomatic: `Wei Xu of his village planned an eastern journey in a year of famine and robbers, and asked Yan Qing to cast.` });
batch.set('s0334', { literal: `Qing divined and said, "You must be careful not to go east—you will meet the qi of sudden violence, yet it will not be robbery."`, idiomatic: `Yan Qing warned him not to travel east: violent qi awaited him, though not common bandits.` });
batch.set('s0335', { literal: `" Xu did not believe him.`, idiomatic: `Wei Xu ignored the warning.` });
batch.set('s0336', { literal: `Qing said, "Since you will surely not stop, you ought to exorcise it: seek west of the outer wall the lone widow's house for a white cockerel and tie it at the prow of the boat."`, idiomatic: `Yan Qing said if he insisted, he must tie a white rooster from a widow west of the wall to the bow as a ward.` });
batch.set('s0337', { literal: `" He searched and obtained only a piebald dog—there was no white one.`, idiomatic: `They could only find a spotted dog, no pure white fowl.` });
batch.set('s0338', { literal: `Qing said, "Piebald is also enough, yet I still regret that its color is not pure—there will remain a small poison, reaching only the six domestic animals; there is nothing further to worry about."`, idiomatic: `Yan Qing said piebald would serve but hinted at leftover venom limited to livestock.` });
batch.set('s0339', { literal: `" When Xu was halfway on the road, the dog suddenly made a very urgent noise as if someone were beating it.`, idiomatic: `Mid-voyage the dog yelped as if flogged.` });
batch.set('s0340', { literal: `When they looked, it was already dead, vomiting more than a dou of black blood.`, idiomatic: `They found it dead, having spewed more than a dou of black blood.` });
batch.set('s0341', { literal: `That evening several white geese on Xu's manor died for no reason, yet Xu's household had no harm.`, idiomatic: `That night his white geese dropped dead, yet every human under his roof was spared.` });
batch.set('s0342', { literal: `Wei Zhao.`, idiomatic: `Wei Zhao` });
batch.set('s0343', { literal: `Wei Zhao was a man of Ruyin.`, idiomatic: `Wei Zhao came from Ruyin.` });
batch.set('s0344', { literal: `He was skilled in the Changes.`, idiomatic: `He was a master of the Zhouyi.` });
batch.set('s0345', { literal: `At the end of life he wrote on a board and handed it to his wife, saying, "After my death there will be great famine and poverty; though it be so, be careful not to sell the house."`, idiomatic: `Dying, he gave his wife a wooden slip: after his death famine would strike, yet she must never sell the house.` });
batch.set('s0346', { literal: `After five years, in spring, there will be an imperial messenger who stops at this post, surnamed Gong—this man owes me gold; take this board to him to collect; do not disobey my words."`, idiomatic: `In five years a courier surnamed Gong would lodge at their post owing him gold—she must present the slip to collect.` });
batch.set('s0347', { literal: `" After Zhao died, his household was greatly destitute and wished to sell the house; remembering her husband's words they always stopped.`, idiomatic: `When want tempted her to sell, she remembered his charge and held the property.` });
batch.set('s0348', { literal: `On the appointed day there was indeed an envoy Gong who halted in the post; the wife then carried the board to demand payment.`, idiomatic: `On the day foretold a Mr. Gong arrived; she brought him the tally for the debt.` });
batch.set('s0349', { literal: `The envoy held the board, dazed, not knowing why.`, idiomatic: `The messenger stared at the slip, baffled.` });
batch.set('s0350', { literal: `The wife said, "At death my husband hand-wrote the board and charged me thus—I dare not be rash."`, idiomatic: `She explained her husband's dying instructions.` });
batch.set('s0351', { literal: `" The messenger pondered long and understood; he said to her, "In what was your worthy husband skilled?"`, idiomatic: `After long thought he asked what arts Wei Zhao had practiced.` });
batch.set('s0352', { literal: `" The wife said, "He was skilled in the Changes, yet never divined for others."`, idiomatic: `She said he knew the Zhouyi but never read for clients.` });
batch.set('s0353', { literal: `" The envoy said, "Ah, I can know!"`, idiomatic: `The envoy exclaimed that he now understood.` });
batch.set('s0354', { literal: `" He ordered yarrow brought and divined; when the hexagram was complete, he clapped his palm and sighed, "Wonderful, Master Wei!"`, idiomatic: `He cast the yarrow himself, then cried out in admiration for Wei Zhao's craft.` });
batch.set('s0355', { literal: `Holding brightness yet hiding his traces—he may be called one who mirrors fortune and privation and pierces good and ill."`, idiomatic: `He praised Wei for hiding brilliance while reading rise and fall with perfect clarity.` });
batch.set('s0356', { literal: `" Thereupon he told Zhao's wife, "I do not owe your worthy husband gold; your worthy husband had gold himself—knowing that after death there would be temporary poverty, he hid gold to await peace; the reason he did not tell sons and wives was fear that when the gold was exhausted hardship would have no end."`, idiomatic: `He explained Wei had buried five hundred jin of gold for the lean years, telling no kin lest they spend it and starve.` });
batch.set('s0357', { literal: `Knowing I am skilled in the Changes, therefore he wrote the board to lodge his meaning."`, idiomatic: `Wei knew the envoy understood the Changes, so he used the slip as cipher.` });
batch.set('s0358', { literal: `The gold is five hundred jin, stored in green jars, covered with bronze platters, buried east of the main hall's head, one zhang from the wall, nine chi into the earth."`, idiomatic: `He directed her to green jars under bronze lids, one zhang from the east wall and nine chi down.` });
batch.set('s0359', { literal: `" The wife returned and dug; all was as divined.`, idiomatic: `She dug and found every coin exactly as foretold.` });
batch.set('s0360', { literal: `Bu Xu.`, idiomatic: `Bu Xu` });
batch.set('s0361', { literal: `Bu Xu, style name Ziyu, was a man of the rear section of the Xiongnu.`, idiomatic: `Bu Xu, courtesy name Ziyu, belonged to the Xiongnu rear division.` });
batch.set('s0362', { literal: `In youth he loved reading the Changes; Guo Pu saw him and sighed, "What I cannot match—yet how can you avoid the misfortune of arms!"`, idiomatic: `While Bu Xu was still a youth poring over the Zhouyi, Guo Pu met him and marveled, "I am not his equal—yet how will he escape dying by the sword?"` });
batch.set('s0363', { literal: `" Xu said, "So it is.`, idiomatic: `Bu Xu calmly replied, "It is as you say."` });
batch.set('s0364', { literal: `My great misfortune is at forty-one; my rank will be minister-general—I shall then meet disaster.`, idiomatic: `He foretold his own doom at forty-one as a minister-general.` });
batch.set('s0365', { literal: `If not that, I will likewise be harmed by a fierce beast.`, idiomatic: `If not that, a savage beast would kill him.` });
batch.set('s0366', { literal: `I likewise have not seen your propitious end."`, idiomatic: `He added that he did not see a peaceful end for Guo Pu either.` });
batch.set('s0367', { literal: `" Pu said, "My misfortune lies south of the Yangzi—I greatly worry about it and have not yet seen an omen of escape.`, idiomatic: `Guo Pu said his peril lay in the south, with no sign of escape.` });
batch.set('s0368', { literal: `Even so, in the south the term may still be extended; staying here will not exceed months."`, idiomatic: `Bu Xu replied that the south might delay fate, but staying north bought only a few months.` });
batch.set('s0369', { literal: `" Xu said, "Do not become a public clerk and you can avoid the various ills."`, idiomatic: `He urged Guo Pu never to take a clerk's post if he wished to live.` });
batch.set('s0370', { literal: `" Pu said, "I cannot avoid being a public clerk—just as you cannot avoid being minister-general."`, idiomatic: `Guo Pu answered that neither could escape the roles fate assigned.` });
batch.set('s0371', { literal: `" Xu said, "Though here there ought to be an imperial son, in the end we will not again serve the two capitals.`, idiomatic: `Bu Xu predicted an imperial scion would rise yet the two capitals would never be restored under them.` });
batch.set('s0372', { literal: `Langye may be served—serve him carefully; the one who will uphold the Jin sacrifices must be this man."`, idiomatic: `He told Guo to cleave to the prince of Langye—the man who would carry the Jin rites.` });
batch.set('s0373', { literal: `" Xu thereupon hid on Mount Longmen.`, idiomatic: `Bu Xu then withdrew to Mount Longmen.` });
batch.set('s0374', { literal: `When Liu Yuanhai arrogated the title, he summoned him as Grand Minister of Agriculture and palace attendant; he firmly pleaded illness and declined.`, idiomatic: `Liu Yuan summoned him as grand minister of agriculture; he feigned illness and refused.` });
batch.set('s0375', { literal: `Yuanhai said, "Each man has his mind—Bu Xu not wishing to be in my court, how does he differ from the Four Lords of the High Ancestor!"`, idiomatic: `Liu Yuan compared his refusal to the recluses Han Gaozu could not compel.` });
batch.set('s0376', { literal: `Let his lofty will be followed."`, idiomatic: `He let Bu Xu keep his hermit pride.` });
batch.set('s0377', { literal: `" Later he was again summoned as Supernumerary Palace Grandee; Xu said to the messenger, "That is not the place where I shall die."`, idiomatic: `When summoned as supernumerary grandee, he told the envoy that office was not where he would perish.` });
batch.set('s0378', { literal: `" When Liu Cong succeeded to the false throne, he summoned him as Grand Master of Ceremonies.`, idiomatic: `Under Liu Cong he was called to be grand master of ceremonies.` });
batch.set('s0379', { literal: `At that time Liu Kun held Bing Province; Cong asked when it could be pacified; Xu answered, "Bing Province is Your Majesty's allotted share—this year taking it is certain."`, idiomatic: `When Liu Cong asked when Liu Kun's Bingzhou would fall, Bu Xu said the stars marked it for the barbarian house that very year.` });
batch.set('s0380', { literal: `" Cong jested, "I would trouble the master to go on one journey—may it be done?"`, idiomatic: `Liu Cong teasingly asked him to lead the campaign himself.` });
batch.set('s0381', { literal: `" Xu said, "The reason I came without finishing my gear was precisely for this journey."`, idiomatic: `Bu Xu replied he had hurried north unprepared precisely to accept that march.` });
batch.set('s0382', { literal: `" Cong was greatly pleased and appointed Xu commissioner on campaign with credentials, General Who Pacifies the North.`, idiomatic: `Delighted, Liu Cong named him credential-bearing commissioner and general who pacifies the north.` });
batch.set('s0383', { literal: `About to depart, he told his younger sister, "This journey—death is my lot; afterward be careful not to fuss."`, idiomatic: `Before leaving he told his sister the campaign meant his death and bade her not to mourn loudly.` });
batch.set('s0384', { literal: `When they attacked Jinyang he was defeated by Kun; Xu was the first to flee in panic and was killed by his commander-in-chief.`, idiomatic: `At the assault on Jinyang he broke before Liu Kun and was cut down by his own commander for cowardice.` });
batch.set('s0385', { literal: `Bao Jing.`, idiomatic: `Bao Jing` });
batch.set('s0386', { literal: `Bao Jing, style name Taixuan, was a man of Donghai.`, idiomatic: `Bao Jing, courtesy name Taixuan, came from Donghai commandery.` });
batch.set('s0387', { literal: `At age five he told his parents, "Originally I was a Li-family child of Quyang; at nine I fell into a well and died."`, idiomatic: `At five he told his parents he had been a Li boy in Quyang who drowned in a well at nine.` });
batch.set('s0388', { literal: `" His parents searched and found the Li family; pushing the inquiry, everything matched verification.`, idiomatic: `They traced the Li household and every detail matched his tale.` });
batch.set('s0389', { literal: `Jing's learning embraced inner and outer; he understood astronomy and the River Chart and Luo Writings; he gradually rose to metropolitan commandant of the middle division of Nanyang and became governor of Nanhai.`, idiomatic: `He mastered Confucian and occult lore, astrology, and Hetu-Luoshu numerology, rising to Nanyang commandant and Nanhai governor.` });
batch.set('s0390', { literal: `Once on inspection he entered the sea, met wind, and was extremely hungry; he took white stones, boiled and ate them to save himself.`, idiomatic: `Caught in a gale at sea on tour, he boiled white flints for food and survived.` });
batch.set('s0391', { literal: `Wang Ji at the time was governor of Guangzhou; entering the privy he suddenly saw two men in black clothes grappling with Ji; after a long while he seized them and obtained two things like crows.`, idiomatic: `When Wang Ji was governor of Guangzhou, he seized two crow-shaped imps that attacked him in the latrine.` });
batch.set('s0392', { literal: `Jing said, "These things are inauspicious."`, idiomatic: `Bao Jing called them ill omens.` });
batch.set('s0393', { literal: `" Ji burned them; they flew straight to heaven; Ji soon was executed and died.`, idiomatic: `Wang Ji burned them; they shot skyward; soon afterward he was executed.` });
batch.set('s0394', { literal: `Jing once met the transcendent Lord Yin, who handed him the oral formulas of the Dao; he died at over a hundred.`, idiomatic: `He met the immortal Yin Jun, received Dao formulas, and died past the century mark.` });
batch.set('s0395', { literal: `Wu Meng.`, idiomatic: `Wu Meng` });
batch.set('s0396', { literal: `Wu Meng was a man of Yuzhang.`, idiomatic: `Wu Meng was a native of Yuzhang.` });
batch.set('s0397', { literal: `In youth he had filial conduct; in summer he commonly did not drive off mosquitoes with his hand, fearing they would leave him and bite his kin.`, idiomatic: `As a boy he let mosquitoes feed on his own flesh so they would not trouble his parents.` });
batch.set('s0398', { literal: `At forty a townsman, Ding Yi, first handed him the divine formula.`, idiomatic: `At forty Ding Yi of his town taught him an esoteric formula.` });
batch.set('s0399', { literal: `Thereupon he returned to Yuzhang; the river waves were very swift; Meng used no boat or oar but with a white feather fan drew on the water and crossed; watchers marveled.`, idiomatic: `Returning to Yuzhang he crossed a raging stream by fanning the water with a white feather fan, astonishing onlookers.` });
batch.set('s0400', { literal: `Yu Liang was governor of Jiang Province; once he fell ill; hearing Meng was spirit-like, he welcomed him and asked how his illness was.`, idiomatic: `Yu Liang, as Jiangzhou governor, summoned him when ill to ask his fate.` });
batch.set('s0401', { literal: `Meng declined, saying the reckoning was exhausted, and asked to prepare a coffin and shroud.`, idiomatic: `Wu Meng answered that Yu Liang's span was spent and asked him to ready coffin clothes.` });

const path = 'translations/current_translation_jinshu.json';
const j = JSON.parse(fs.readFileSync(path, 'utf8'));
for (const s of j.sentences) {
  const t = batch.get(s.id);
  if (t) {
    s.literal = t.literal;
    s.idiomatic = t.idiomatic;
  }
}
fs.writeFileSync(path, JSON.stringify(j, null, 2) + '\n');
console.log('batch4 applied', batch.size);
