import fs from 'node:fs';

const batch = new Map();

batch.set('s0702', { literal: `" Ce said, "This old man is senile—I will not act as matchmaker."`, idiomatic: `Linghu Ce replied that he was too old to broker weddings.` });
batch.set('s0703', { literal: `It happened that Prefect Tian Bao of the commandery, through Ce, sought the daughter of his townsman Zhang Gongzheng for his son; in the second month of spring the marriage was completed.`, idiomatic: `Prefect Tian Bao then used Linghu Ce as intermediary to win Zhang Gongzheng's daughter for his son, and the pair wed that mid-spring.` });
batch.set('s0704', { literal: `The commandery chief clerk Zhang Zhai dreamed a horse galloped up a mountain, circled his house three full turns, yet he saw only pines and cypresses and could not find the gate.`, idiomatic: `Chief Clerk Zhang Zhai dreamed of a horse charging uphill, cantering three circuits around his home amid evergreens, with no doorway in sight.` });
batch.set('s0705', { literal: `Dan said, "The horse belongs to li; li is fire.`, idiomatic: `Suo Dan said the horse stood for the trigram li, and li meant fire.` });
batch.set('s0706', { literal: `Fire means calamity.`, idiomatic: `Fire portended disaster.` });
batch.set('s0707', { literal: `A man on a mountain forms the graph xiong ('inauspicious').`, idiomatic: `Man plus mountain spelled the character for ill omen.` });
batch.set('s0708', { literal: `Yet seeing only pine and cypress is the image of a tomb gate.`, idiomatic: `Seeing only evergreens evoked a cemetery gate.` });
batch.set('s0709', { literal: `Not knowing where the gate is means there is no gate.`, idiomatic: `The missing gate meant there would be no escape.` });
batch.set('s0710', { literal: `Three circuits mean three cycles.`, idiomatic: `Three rounds foretold three years.` });
batch.set('s0711', { literal: `After three years there will certainly be a great disaster.`, idiomatic: `A major catastrophe would strike within three years.` });
batch.set('s0712', { literal: `" Zhai indeed was executed for plotting rebellion.`, idiomatic: `Zhang Zhai was later put to death for treason, as foretold.` });
batch.set('s0713', { literal: `At first Suo Chong dreamed two coffins fell from the sky before Chong; Dan said, "A coffin is zhi ('office'); a capital noble ought to recommend you.`, idiomatic: `Suo Chong dreamed twin coffins drop from heaven; Suo Dan read "coffin" as high office and predicted a metropolitan patron would nominate him.` });
batch.set('s0714', { literal: `Two offices mean repeated promotions.`, idiomatic: `Two coffins meant two successive advancements.` });
batch.set('s0715', { literal: `" Before long Minister of Education Wang Rong wrote instructing the prefect to recommend Chong; the prefect first appointed Chong merit clerk and then nominated him filial-incorrupt.`, idiomatic: `Wang Rong soon wrote the prefect, who first named Suo Chong merit clerk and then raised him as filial-incorrupt.` });
batch.set('s0716', { literal: `Later Chong dreamed a barbarian stripped his upper garment and came to Chong.`, idiomatic: `Suo Chong later dreamed a tribesman doff his jacket and approach him.` });
batch.set('s0717', { literal: `Dan said, "The barbarian removes the middle from shang; the lower half is the graph nan ('male'); the barbarian is a yin class of being—your wife shall bear a son.`, idiomatic: `Suo Dan parsed the "barbarian" glyph: remove the middle stroke of shang and the lower half reads "male," so a foreign yin omen meant his wife would deliver a boy.` });
batch.set('s0718', { literal: `" In the end it was as he said.`, idiomatic: `The birth matched his reading exactly.` });
batch.set('s0719', { literal: `Song Que dreamed someone inside the inner chambers wore crimson; Que held two staves and beat him fiercely.`, idiomatic: `Song Que dreamed a red-clad intruder in the women's quarters whom he struck with twin rods.` });
batch.set('s0720', { literal: `Dan said, "Someone inside the inner chambers is the graph rou ('flesh').`, idiomatic: `Suo Dan said "person within inner rooms" formed the character for flesh.` });
batch.set('s0721', { literal: `Flesh color is red.`, idiomatic: `Flesh implied crimson garb.` });
batch.set('s0722', { literal: `Two staves are the image of chopsticks.`, idiomatic: `Twin sticks stood for chopsticks.` });
batch.set('s0723', { literal: `Beating fiercely means eating meat to satiety.`, idiomatic: `The beating meant feasting on meat until full.` });
batch.set('s0724', { literal: `" Soon it likewise verified.`, idiomatic: `The dream soon proved true.` });
batch.set('s0725', { literal: `Huang Ping asked Dan, saying, "Last night I dreamed horses dancing in my house and several dozen men clapping toward the horses—what sort of auspice is this?"`, idiomatic: `Huang Ping asked Suo Dan about a dream of capering horses and a crowd applauding them indoors.` });
batch.set('s0726', { literal: `" Dan said, "The horse is fire; dancing means fire rising.`, idiomatic: `Suo Dan said horses signified fire, and dancing meant flames mounting.` });
batch.set('s0727', { literal: `Clapping toward the horse means men who fight fire.`, idiomatic: `Applauding the steeds depicted firefighters at work.` });
batch.set('s0728', { literal: `" Before Ping returned home, fire broke out.`, idiomatic: `A blaze erupted before Huang Ping reached his door.` });
batch.set('s0729', { literal: `Suo Sui dreamed two horned documents came east to Sui; the large horn was rotten, the small horn bore an inscription and a leather satchel hung from the horn; one was in front, one behind.`, idiomatic: `Suo Sui dreamed two horn-marked writs arrive from the east, one decayed, one inscribed, with a tagged pouch and one horn leading, one trailing.` });
batch.set('s0730', { literal: `Dan said, "The large horn rotten means a decayed coffin board.`, idiomatic: `The crumbling great horn stood for rotten coffin wood.` });
batch.set('s0731', { literal: `The small horn having an inscription means the inscription states the destination.`, idiomatic: `The smaller horn's text marked where the blow would fall.` });
batch.set('s0732', { literal: `One in front—that configuration was inauspicious for Dan.`, idiomatic: `The foremost placement spelled personal misfortune for Suo Dan.` });
batch.set('s0733', { literal: `One behind—'behind' is 'back,' meaning contrary.`, idiomatic: `The rear position read as "contrary," a breach of taboo.` });
batch.set('s0734', { literal: `There ought to be a calamity concerning 'contrary.'`, idiomatic: `He foresaw news tied to that reversal.` });
batch.set('s0735', { literal: `" At that time Sui's father was in the east; within three days ill tidings arrived.`, idiomatic: `Suo Sui's father was eastward; within three days mourning news came.` });
batch.set('s0736', { literal: `Commandery merit clerk Zhang Miao once went on mission to the province and dreamed a wolf gnawed one foot.`, idiomatic: `Merit clerk Zhang Miao, traveling to the provincial seat, dreamed a wolf chewed his foot.` });
batch.set('s0737', { literal: `Dan said, "Foot flesh gnawed away forms the graph que ('withdraw').`, idiomatic: `Suo Dan read gnawed foot-flesh as the character for retreat.` });
batch.set('s0738', { literal: `" It happened that eastern barbarians rebelled, and he therefore did not go.`, idiomatic: `Eastern tribes rose in revolt, so the journey was canceled.` });
batch.set('s0739', { literal: `In all he prognosticated, nothing failed to verify.`, idiomatic: `Every omen he read came true.` });
batch.set('s0740', { literal: `Prefect Yin Dan sought his divination books; Dan said, "Long ago I entered the Grand Academy; through one old man as host—who knew everything and hid his name, somewhat like a recluse—I followed the old man to ask the art of dream divination, hoping to extend my mean skill; I examined and spoke from insight; truly there are no books."`, idiomatic: `Prefect Yin Dan asked for written manuals; Suo Dan swore he had learned dream lore from an anonymous sage at the academy and owned no texts, only tested judgment.` });
batch.set('s0741', { literal: `" Dan appointed him libationer of the west pavilion; Dan declined, saying, "In youth I had no mountain-forest resolve; I studied in the capital and befriended leading men of the age; as the Central States were not tranquil, I wished to cultivate my aims to the end of my years.`, idiomatic: `Yin Dan named him west-pavilion libationer, but Suo Dan refused, citing no hermit vocation, capital schooling, and a wish to retire quietly amid turmoil.` });
batch.set('s0742', { literal: `Old age has also arrived; I do not seek renown.`, idiomatic: `He added that old age had come and he craved no fame.` });
batch.set('s0743', { literal: `Moreover in youth I did not practice diligence; in age I lack clerkly capacity; in the Meng-si twilight of life I dare not accept the command."`, idiomatic: `He pleaded no talent for administration and declined office in his declining years.` });
batch.set('s0744', { literal: `" Dan therefore presented him bundled silk and monthly sheep and wine.`, idiomatic: `The prefect instead sent silk bundles and monthly provisions of mutton and wine.` });
batch.set('s0745', { literal: `At age seventy-five he died at home.`, idiomatic: `Suo Dan died at home aged seventy-five.` });
batch.set('s0746', { literal: `Meng Qin.`, idiomatic: `Meng Qin` });
batch.set('s0747', { literal: `Meng Qin was a man of Luoyang.`, idiomatic: `Meng Qin came from Luoyang.` });
batch.set('s0748', { literal: `He had the arts of Zuo Ci and Liu Gen; the common people were deluded and flocked to him.`, idiomatic: `He wielded thaumaturgy like Zuo Ci and Liu Gen, drawing credulous crowds.` });
batch.set('s0749', { literal: `Fu Jian summoned him to Chang'an, detested his misleading the masses, and ordered Fu Rong to execute him.`, idiomatic: `Fu Jian called him to Chang'an, loathed his sway over the populace, and told Fu Rong to kill him.` });
batch.set('s0750', { literal: `Before long Qin arrived; Rong detained him and then feasted the commandery staff; when the wine was warm he signaled attendants to seize Qin.`, idiomatic: `Meng Qin appeared; Fu Rong detained him, wined his officials, then signaled guards to arrest him mid-banquet.` });
batch.set('s0751', { literal: `Qin transformed into a whirlwind and flew out beyond the compound.`, idiomatic: `Meng Qin became a whirlwind and shot past the manor walls.` });
batch.set('s0752', { literal: `Shortly someone reported him east of the city; Rong sent riders in pursuit; as they nearly caught him he was suddenly far away, or there were troops blocking battle, or ravines lay ahead so the horses could not cross; thus his whereabouts were unknown.`, idiomatic: `Riders chased reports east of town, but phantoms of armies and gorges kept them from closing in, and he vanished.` });
batch.set('s0753', { literal: `Toward the end of Fu Jian's reign he was seen again in Qingzhou.`, idiomatic: `Late in Fu Jian's rule he resurfaced in Qingzhou.` });
batch.set('s0754', { literal: `Fu Lang searched for him; he entered an island in the sea.`, idiomatic: `Fu Lang tracked him to a sea isle and lost him there.` });
batch.set('s0755', { literal: `Wang Jia.`, idiomatic: `Wang Jia` });
batch.set('s0756', { literal: `Wang Jia, style name Zinian, was a man of Anyang in Longxi.`, idiomatic: `Wang Jia, courtesy Zinian, hailed from Anyang in Longxi.` });
batch.set('s0757', { literal: `His bearing was light and his looks ugly; outwardly he seemed deficient, yet he was keen and bright within.`, idiomatic: `He seemed slovenly and homely yet was razor-sharp inside.` });
batch.set('s0758', { literal: `Witty, fond of speech and laughter, he ate not the five grains, wore not fine silks, purified himself on qi, and did not mingle with the world.`, idiomatic: `He jested constantly, shunned grain and brocade, lived on breath discipline, and shunned society.` });
batch.set('s0759', { literal: `He hid in the valley of Dongyang, dwelling in cliff-hewn caves; disciples who received his teaching were several hundred, and they too dwelt in caves.`, idiomatic: `He herded hundreds of pupils into cliff caverns near Dongyang.` });
batch.set('s0760', { literal: `At the end of Shi Jilong's reign he abandoned his followers, came to Chang'an, and secretly hid on Mount Zhongnan, tying up a hut and stopping there.`, idiomatic: `When Shi Hu's regime collapsed he left his flock for Chang'an and built a hidden hut on Zhongnan.` });
batch.set('s0761', { literal: `Disciples heard and again followed him; he therefore moved to Mount Daoshou.`, idiomatic: `Students found him again, so he relocated to Mount Daoshou.` });
batch.set('s0762', { literal: `Fu Jian repeatedly summoned him but he would not rise; dukes and marquises downward all went in person to consult him; gentlemen of enthusiasm none failed to honor him as teacher.`, idiomatic: `Fu Jian's repeated calls went ignored while nobles and scholars made pilgrimages to study under him.` });
batch.set('s0763', { literal: `On matters of the present age he answered as each question came.`, idiomatic: `He fielded contemporary questions without hesitation.` });
batch.set('s0764', { literal: `He loved to make parables; his manner was like jest.`, idiomatic: `He spoke in riddling parables like a comic.` });
batch.set('s0765', { literal: `When he spoke of things not yet happened, his words were like prophecy records; at the time few could understand; after events passed, all verified.`, idiomatic: `His future-tense riddles baffled listeners until hindsight proved each clue.` });
batch.set('s0766', { literal: `When Fu Jian was about to march south he sent an envoy to ask him.`, idiomatic: `On the eve of Fu Jian's southern campaign an envoy sought his oracle.` });
batch.set('s0767', { literal: `Jia said, "Diamond hard, fire strong."`, idiomatic: `Wang Jia answered with the gnomic line "Vajra fierce, fire fierce."` });
batch.set('s0768', { literal: `" Thereupon he mounted the envoy's horse, straightened cap and robes, slowly rode east several hundred paces, then whipped the horse in a gallop back, cast off clothes, threw away cap and shoes, returned, dismounted, squatted on a couch, and said nothing at all.`, idiomatic: `He borrowed the courier's mount, paraded eastward, wheeled at a gallop, shed cap and boots, then sat mute on a bench.` });
batch.set('s0769', { literal: `The envoy returned and reported; Jian spoke nothing, again sent to ask, saying, "How fares my dynastic fortune?"`, idiomatic: `The baffled envoy reported; Fu Jian sent again to ask how long his line would endure.` });
batch.set('s0770', { literal: `" Jia said, "Weiyang."`, idiomatic: `Wang Jia replied "Weiyang," which courtiers misread as endless blessing.` });
batch.set('s0771', { literal: `" All deemed it auspicious.`, idiomatic: `Everyone took it for a promise of enduring rule.` });
batch.set('s0772', { literal: `The next year, guiwei, he was defeated south of the Huai; this is what is meant by the wei year still having calamity.`, idiomatic: `The next year guiwei brought disaster at Fei River—"not ended" had meant the wei year would still know woe.` });
batch.set('s0773', { literal: `Those who waited on him, if utterly sincere then saw him; if not utterly sincere then he hid his form and was not seen.`, idiomatic: `He appeared only to the utterly sincere and stayed invisible to half-hearted callers.` });
batch.set('s0774', { literal: `His clothes hung on racks, shoes and staff still there; if someone wished to take his garments they could never reach them; standing on tiptoe to take them, the clothes rack grew higher, yet the room was not large; covering staff and other objects likewise behaved so.`, idiomatic: `His robe and staff seemed ordinary yet eluded grasp, the rack rising when stretched for, though the chamber never widened.` });
batch.set('s0775', { literal: `When Yao Chang entered Chang'an he treated Jia as in Fu Jian's former practice, forced him to accompany himself, and consulted him on every affair.`, idiomatic: `Yao Chang, conquering Chang'an, courted Wang Jia as Fu Jian had and dragooned him into counsel.` });
batch.set('s0776', { literal: `When Chang was locked with Fu Deng in stalemate he asked Jia, "Can I kill Fu Deng and settle All-under-Heaven?"`, idiomatic: `During the standoff with Fu Deng, Yao Chang asked whether he could slay his rival and pacify the realm.` });
batch.set('s0777', { literal: `" Jia said, "In rough terms you will obtain it."`, idiomatic: `Wang Jia answered, "You will gain it in part."` });
batch.set('s0778', { literal: `" Chang angrily said, "Obtain is obtain—what is this 'in part'!"`, idiomatic: `Yao Chang fumed that victory should be total, not partial.` });
batch.set('s0779', { literal: `" Thereupon he executed him.`, idiomatic: `He had Wang Jia beheaded in wrath.` });
batch.set('s0780', { literal: `Before this, the monk Dao'an had said to Jia, "The world's troubles are just swelling; you may go."`, idiomatic: `Earlier Shih Dao'an had urged him to flee mounting chaos.` });
batch.set('s0781', { literal: `" Jia answered, "You may go first; I have a debt unpaid and cannot yet leave."`, idiomatic: `Wang Jia answered that Dao'an should leave first while he still owed fate a reckoning.` });
batch.set('s0782', { literal: `" Before long Dao'an died; by this time Jia was executed—this is what is meant by 'debt.'`, idiomatic: `Dao'an died soon after; Wang Jia's execution fulfilled the dark sense of "debt."` });
batch.set('s0783', { literal: `When Fu Deng heard Jia had died he set up an altar and wept for him, posthumously awarding Grand Preceptor and posthumous name Wen.`, idiomatic: `Fu Deng mourned him with rites and posthumous honors as Grand Preceptor Wen.` });
batch.set('s0784', { literal: `When Chang died, Chang's son Xing, style name Zilue, then killed Deng—this is what 'in rough terms obtain it' referred to.`, idiomatic: `Yao Chang's son Yao Xing, whose courtesy was Zilue, later slew Fu Deng—fulfilling the cryptic "partial gain."` });
batch.set('s0785', { literal: `On the day Jia died, someone saw him on the Long uplands.`, idiomatic: `The day he died, witnesses still saw him walking the Long plateau.` });
batch.set('s0786', { literal: `The "Pulling Three Songs Prophecy" that he composed—after events passed all verified; successive ages still transmit it.`, idiomatic: `His doggerel prophecy cycle proved true in every line and stayed in folk memory.` });
batch.set('s0787', { literal: `He also wrote the "Gathered Relics Record" in ten scrolls; its records are mostly uncanny and strange, and today circulates in the world.`, idiomatic: `His ten-scroll miscellany of marvels remains in print.` });
batch.set('s0788', { literal: `Monk She`, idiomatic: `The monk She (Seng She)` });
batch.set('s0789', { literal: `Seng She was a man of the Western Regions; his surname is not known.`, idiomatic: `Seng She came from the Western Regions; his family name was lost.` });
batch.set('s0790', { literal: `In youth he became a monk; in Fu Jian's time he entered Chang'an.`, idiomatic: `He tonsured young and reached Chang'an under Fu Jian.` });
batch.set('s0791', { literal: `Empty and still he ingested qi, ate not the five grains, could travel five hundred li in a day, and spoke of things not yet happened with verification like pointing at his palm.`, idiomatic: `He lived on breath, crossed five hundred li daily without grain, and foretold the future with uncanny precision.` });
batch.set('s0792', { literal: `He could by secret invocations bring down divine dragons; whenever drought came, Jian constantly had him curse dragons to beg rain.`, idiomatic: `He summoned rain-dragons by esoteric spells whenever drought struck.` });
batch.set('s0793', { literal: `Before long a dragon descended into the bowl; Heaven at once sent great rain; Jian and the host of ministers went in person to the bowl to observe it.`, idiomatic: `A dragon coiled in an alms bowl and heaven opened; Fu Jian and his court peered in.` });
batch.set('s0794', { literal: `He died in Chang'an.`, idiomatic: `He passed away in Chang'an.` });
batch.set('s0795', { literal: `Later, after long drought, Fu Jian sighed, "If Duke She were alive, how would I worry over this!"`, idiomatic: `Years of drought later made Fu Jian lament that without She their rains would never return.` });
batch.set('s0796', { literal: `Guo Wu.`, idiomatic: `Guo Wu` });
batch.set('s0797', { literal: `Guo Wu was a man of Xiping.`, idiomatic: `Guo Wu hailed from Xiping.` });
batch.set('s0798', { literal: `In youth he understood the Laozi and Changes; he served as commandery chief clerk.`, idiomatic: `Youthful mastery of the Laozi and Zhouyi won him the chief clerk's post.` });
batch.set('s0799', { literal: `In the last years of Zhang Tianxi, whenever the Fu clan raised questions of a western campaign, Prefect Zhao Ning had Wu divine it; Wu said, "If by the fifteenth day of the second month within the commandery a prisoner escapes, the eastern army will arrive and Liang's mandate will end."`, idiomatic: `As Former Qin threatened Hexi, Prefect Zhao Ning had Guo Wu cast lots: a jailbreak on the fifteenth of the second month would herald eastern invasion and the fall of Former Liang.` });
batch.set('s0800', { literal: `" Ning therefore issued orders to the subordinate counties.`, idiomatic: `Zhao Ning wired every county to tighten the jails.` });
batch.set('s0801', { literal: `On the fifteenth day the Xianbei Zhejue presented horses to Ning; Ning, angry they were not swift mounts, confined them in the inner stable; the Xianbei feared and fled by night.`, idiomatic: `On that day Xianbei herdsmen delivered horses Zhao Ning disliked and locked up, provoking a night stampede that broke custody.` });

const path = 'translations/current_translation_jinshu.json';
const j = JSON.parse(fs.readFileSync(path, 'utf8'));
for (const s of j.sentences) {
  const t = batch.get(s.id);
  if (t) {
    s.literal = t.literal;
    s.idiomatic = t.idiomatic;
  }
}
fs.writeFileSync(path, JSON.stringify(j, null, 2) + '\n');
console.log('batch8 applied', batch.size);
