#!/usr/bin/env python3
import json

T = {
"s1301": ("Yinjiang, east of the prefecture seat.", "Yinjiang lies east of the prefecture seat."),
"s1302": ("Formerly the Siyin River Native Official Office, in the Yuan subordinate to the Sinan Pacification Commission.", "It was formerly the Siyin River Native Official Office, subordinate in the Yuan to the Sinan Pacification Commission."),
"s1303": ("In the third month of Yongle 12 it belonged to the prefecture.", "In the third month of Yongle 12 it came under the prefecture."),
"s1304": ("In the sixth month of Hongzhi 7 it was changed to Yinjiang County.", "In the sixth month of Hongzhi 7 it was changed to Yinjiang County."),
"s1305": ("The Yanhe Youxi Native Official Office, northeast of the prefecture seat.", "The Yanhe Youxi Native Official Office lies northeast of the prefecture seat."),
"s1306": ("Established in the tenth month of Hongwu 7, subordinate to the Sinan Pacification Commission.", "It was established in the tenth month of Hongwu 7 and subordinated to the Sinan Pacification Commission."),
"s1307": ("In the third month of Yongle 12 it belonged to the prefecture.", "In the third month of Yongle 12 it came under the prefecture."),
"s1308": ("The Langxi Barbarian Native Official Office, east of the prefecture seat.", "The Langxi Barbarian Native Official Office lies east of the prefecture seat."),
"s1309": ("Established in the tenth month of Hongwu 7, subordinate to the Sinan Pacification Commission.", "It was established in the tenth month of Hongwu 7 and subordinated to the Sinan Pacification Commission."),
"s1310": ("In the third month of Yongle 12 it belonged to Wuluo Prefecture.", "In the third month of Yongle 12 it came under Wuluo Prefecture."),
"s1311": ("In the fifth month of Zhengtong 3 the prefecture was abolished and it came under jurisdiction.", "In the fifth month of Zhengtong 3 Wuluo Prefecture was abolished and it came under Sinan Prefecture."),
"s1312": ("There is the Juexi Barbarian Native Official Office, also established in the tenth month of Hongwu 7; soon abolished.", "There is the Juexi Barbarian Native Official Office, also established in the tenth month of Hongwu 7; it was soon abolished."),
"s1313": ("Sizhou Prefecture was the Yuan Sizhou Pacification Commission.", "Sizhou Prefecture was the Yuan Sizhou Pacification Commission."),
"s1314": ("In the second month of Yongle 11 it was changed to a prefecture, subordinate to the Guizhou Provincial Administration Commission.", "In the second month of Yongle 11 it was changed to a prefecture and subordinated to the Guizhou Provincial Administration Commission."),
"s1315": ("It administers four native official offices.", "It administers four native official offices."),
"s1316": ("Seven hundred fifty li west from the provincial administration commission.", "It lies seven hundred fifty li west of the provincial administration commission."),
"s1317": ("The Duping Eyi Stream Barbarian Native Official Office, attached.", "The Duping Eyi Stream Barbarian Native Official Office (seat-attached)."),
"s1318": ("Established in Hongwu 6; abolished in year 25.", "It was established in Hongwu 6 and abolished in Hongwu 25."),
"s1319": ("In the third month of Yongle 12 it was re-established.", "In the third month of Yongle 12 it was re-established."),
"s1320": ("To the south is E Mountain.", "To the south is E Mountain."),
"s1321": ("To the northwest is Jiangtou Mountain.", "To the northwest is Jiangtou Mountain."),
"s1322": ("To the east is the Yi Stream.", "To the east is the Yi Stream."),
"s1323": ("To the northeast is Ping Stream; above it is a pass; in the third month of Hongwu 22 Pingxi Guard was established here, subordinate to the Huguang regional command; in the eleventh month of Wanli 29 it was changed to Guizhou, and in the fourth month of year 31 it returned to Huguang.", "To the northeast is Ping Stream; above it is a pass; in the third month of Hongwu 22 Pingxi Guard was established here, subordinate to the Huguang regional command; in the eleventh month of Wanli 29 it was transferred to Guizhou, and in the fourth month of Wanli 31 it returned to Huguang."),
"s1324": ("Also there is Nianyu Pass.", "Also there is Nianyu Pass."),
"s1325": ("To the south is Huangtu Pass.", "To the south is Huangtu Pass."),
"s1326": ("Also to the northeast is Huangzhou Post Station; the road leads out to Yuan Prefecture in Huguang.", "Also to the northeast is Huangzhou Post Station; the road leads out to Yuan Prefecture in Huguang."),
"s1327": ("The Dusu Barbarian Native Official Office, west of the prefecture seat.", "The Dusu Barbarian Native Official Office lies west of the prefecture seat."),
"s1328": ("Established in the third month of Yongle 12, subordinate to the prefecture.", "It was established in the third month of Yongle 12 and subordinated to the prefecture."),
"s1329": ("The Shixi Native Official Office, north of the prefecture seat.", "The Shixi Native Official Office lies north of the prefecture seat."),
"s1330": ("In the Yuan the Shixi Yangtou Native Official Office.", "In the Yuan it was the Shixi Yangtou Native Official Office."),
"s1331": ("Renamed in Hongwu 5, subordinate to the Huguang Yuan Prefecture Guard.", "It was renamed in Hongwu 5 and subordinated to the Huguang Yuan Prefecture Guard."),
"s1332": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1333": ("To the east is Shixi.", "To the east is Shixi."),
"s1334": ("The Huangdao Stream Native Official Office, northeast of the prefecture seat.", "The Huangdao Stream Native Official Office lies northeast of the prefecture seat."),
"s1335": ("In the Yuan subordinate to the Sizhou Pacification Commission.", "In the Yuan it was subordinate to the Sizhou Pacification Commission."),
"s1336": ("In the third month of Yongle 12 it belonged to the prefecture.", "In the third month of Yongle 12 it came under the prefecture."),
"s1337": ("To the southwest is Huangdao Stream.", "To the southwest is Huangdao Stream."),
"s1338": ("Zhenyuan Prefecture was the Yuan Zhenyuan Prefecture, subordinate to the Sizhou Pacification Office.", "Zhenyuan Prefecture was the Yuan Zhenyuan Prefecture, subordinate to the Sizhou Pacification Office."),
"s1339": ("In Hongwu 4 it was reduced to Zhenyuan Prefecture, subordinate to the Sinan Pacification Commission.", "In Hongwu 4 it was reduced to Zhenyuan Prefecture and subordinated to the Sinan Pacification Commission."),
"s1340": ("In the sixth month of Hongwu 5 it was directly subordinate to Huguang.", "In the sixth month of Hongwu 5 it was placed under direct Huguang jurisdiction."),
"s1341": ("In the second month of Yongle 11 Zhenyuan Prefecture was established at the prefecture seat, subordinate to the Guizhou Provincial Administration Commission.", "In the second month of Yongle 11 Zhenyuan Prefecture was established at the prefecture seat and subordinated to the Guizhou Provincial Administration Commission."),
"s1342": ("In the fifth month of Zhengtong 3 the prefecture was abolished and merged into it.", "In the fifth month of Zhengtong 3 the prefecture was abolished and merged into it."),
"s1343": ("It administers two counties and three native official offices.", "It administers two counties and three native official offices."),
"s1344": ("Five hundred thirty li west from the provincial administration commission.", "It lies five hundred thirty li west of the provincial administration commission."),
"s1345": ("Zhenyuan, attached.", "Zhenyuan (seat-attached county)."),
"s1346": ("Formerly the Zhenyuan Stream Cave Jinrong Jinda Barbarian Native Official Office, established in the second month of Hongwu 2, subordinate to the Sinan Pacification Commission.", "It was formerly the Zhenyuan Stream Cave Jinrong Jinda Barbarian Native Official Office, established in the second month of Hongwu 2 and subordinated to the Sinan Pacification Commission."),
"s1347": ("In the third month of Yongle 12 it belonged to the prefecture.", "In the third month of Yongle 12 it came under the prefecture."),
"s1348": ("In the fifth month of Zhengtong 3 it was changed to belong to the prefecture.", "In the fifth month of Zhengtong 3 it came under the prefecture."),
"s1349": ("In the tenth month of Hongzhi 7 it was changed to Zhenyuan County.", "In the tenth month of Hongzhi 7 it was changed to Zhenyuan County."),
"s1350": ("To the north is Shiya Mountain.", "To the north is Shiya Mountain."),
"s1351": ("To the east is Zhonghe Mountain, named for two streams flowing between them.", "To the east is Zhonghe Mountain, named because two streams flow between them."),
"s1352": ("To the northeast is Tie Mountain.", "To the northeast is Tie Mountain."),
"s1353": ("Also to the east is Guanyin Mountain; there is Machang Slope.", "Also to the east is Guanyin Mountain; there is Machang Slope."),
"s1354": ("To the southeast is Babang Mountain.", "To the southeast is Babang Mountain."),
"s1355": ("To the west is Pingmao Mountain.", "To the west is Pingmao Mountain."),
"s1356": ("To the south is the Zhenyang River, also called Zhennan River, also called Wushui; upstream it receives the waters of Xinglong, Huangping, and other places; flowing east three hundred li it enters the Yuan River.", "To the south is the Zhenyang River, also called Zhennan River and Wushui; upstream it receives waters from Xinglong, Huangping, and other places; flowing east three hundred li it enters the Yuan River."),
"s1357": ("Also to the northeast is Tiexi, issuing from Tie Mountain and flowing down into the Zhenyang River.", "Also to the northeast is Tiexi, issuing from Tie Mountain and flowing down into the Zhenyang River."),
"s1358": ("Also to the west is Youzha Pass.", "Also to the west is Youzha Pass."),
"s1359": ("There are Jiaoxi Pass and Meixi Pass.", "There are Jiaoxi Pass and Meixi Pass."),
"s1360": ("Also there is Qinglang Pass; Qinglang Guard is administered here; also to the west is Pianqiao, where Pianqiao Guard is located — all established in the fourth month of Hongwu 23.", "Also there is Qinglang Pass, where Qinglang Guard is administered; also to the west is Pianqiao, where Pianqiao Guard is located — all established in the fourth month of Hongwu 23."),
"s1361": ("To the southwest is Zhenyuan Guard, established in the seventh month of Hongwu 22.", "To the southwest is Zhenyuan Guard, established in the seventh month of Hongwu 22."),
"s1362": ("All subordinate to the Huguang regional command; in the eleventh month of Wanli 29 all were changed to Guizhou, and in the fourth month of year 31 they returned to Huguang.", "All were subordinate to the Huguang regional command; in the eleventh month of Wanli 29 all were transferred to Guizhou, and in the fourth month of Wanli 31 they returned to Huguang."),
"s1363": ("Shibing, southwest of the prefecture seat.", "Shibing lies southwest of the prefecture seat."),
"s1364": ("Formerly the Shibing Barbarian Native Official Office, established in Hongwu 5, subordinate to the Sinan Pacification Commission.", "It was formerly the Shibing Barbarian Native Official Office, established in Hongwu 5 and subordinated to the Sinan Pacification Commission."),
"s1365": ("In the third month of Yongle 12 it belonged to the prefecture.", "In the third month of Yongle 12 it came under the prefecture."),
"s1366": ("In the seventh month of Zhengtong 9 it was changed to a county.", "In the seventh month of Zhengtong 9 it was changed to a county."),
"s1367": ("In the fourth month of Tianqi 1 it was abolished.", "In the fourth month of Tianqi 1 it was abolished."),
"s1368": ("In the eleventh month of Chongzhen 4 it was re-established.", "In the eleventh month of Chongzhen 4 it was re-established."),
"s1369": ("To the south is the Hong River, that is, the Zhenyang River.", "To the south is the Hong River — that is, the Zhenyang River."),
"s1370": ("The Pianqiao Native Official Office, west of the prefecture seat.", "The Pianqiao Native Official Office lies west of the prefecture seat."),
"s1371": ("In the Yuan the Pianqiao Central Stockade Barbarian Military-Civil Native Official Office.", "In the Yuan it was the Pianqiao Central Stockade Barbarian Military-Civil Native Official Office."),
"s1372": ("Re-established in Hongwu 5, subordinate to the Sinan Pacification Commission.", "It was re-established in Hongwu 5 and subordinated to the Sinan Pacification Commission."),
"s1373": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1374": ("The Qiongshui Fifteen Caves Barbarian Native Official Office, east of the prefecture seat.", "The Qiongshui Fifteen Caves Barbarian Native Official Office lies east of the prefecture seat."),
"s1375": ("In the Yuan Qiongshui County.", "In the Yuan it was Qiongshui County."),
"s1376": ("In Hongwu 5 five native official offices were established — Tuanluo, Demin, Xia'ai, Pidai, and Qiongshui — subordinate to the Sizhou Pacification Commission.", "In Hongwu 5 five native official offices were established — Tuanluo, Demin, Xia'ai, Pidai, and Qiongshui — subordinate to the Sizhou Pacification Commission."),
"s1377": ("In year 29 four offices were merged into the Qiongshui Office, subordinate to the Sinan Pacification Commission.", "In Hongwu 29 four offices were merged into the Qiongshui Office, subordinate to the Sinan Pacification Commission."),
"s1378": ("In the third month of Yongle 12 it belonged to the prefecture.", "In the third month of Yongle 12 it came under the prefecture."),
"s1379": ("The Zhenpou Six Caves Hengpo and Other Places Native Official Office, west of the prefecture seat.", "The Zhenpou Six Caves Hengpo and Other Places Native Official Office lies west of the prefecture seat."),
"s1380": ("Formerly the Zhenpou, Liudong, and Hengpo native official offices, established in Hongwu 22, subordinate to Zhenyuan Guard; later merged into one office.", "It was formerly the Zhenpou, Liudong, and Hengpo native official offices, established in Hongwu 22 and subordinate to Zhenyuan Guard; later they were merged into one office."),
"s1381": ("Tongren Prefecture was formerly territory of the Sizhou Pacification Commission.", "Tongren Prefecture was originally territory of the Sizhou Pacification Commission."),
"s1382": ("In the second month of Yongle 11 Tongren Prefecture was established.", "In the second month of Yongle 11 Tongren Prefecture was established."),
"s1383": ("It administers one county and five native official offices.", "It administers one county and five native official offices."),
"s1384": ("Seven hundred seventy li southwest from the provincial administration commission.", "It lies seven hundred seventy li southwest of the provincial administration commission."),
"s1385": ("Tongren, attached.", "Tongren (seat-attached county)."),
"s1386": ("In the Yuan the Tongren Greater and Lesser River and Other Places Barbarian Military-Civil Native Official Office, subordinate to the Sizhou Pacification Office.", "In the Yuan it was the Tongren Greater and Lesser River and Other Places Barbarian Military-Civil Native Official Office, subordinate to the Sizhou Pacification Office."),
"s1387": ("At the beginning of Hongwu it was re-established as the Tongren Native Official Office, subordinate to the Sinan Pacification Commission.", "At the beginning of the Hongwu reign it was re-established as the Tongren Native Official Office and subordinated to the Sinan Pacification Commission."),
"s1388": ("In the third month of Yongle 12 the prefectural seat was established here.", "In the third month of Yongle 12 the prefectural seat was established here."),
"s1389": ("In the fourth month of Wanli 26 it was changed to a county.", "In the fourth month of Wanli 26 it was changed to a county."),
"s1390": ("To the south is Tongya Mountain.", "To the south is Tongya Mountain."),
"s1391": ("Also there is Xinkeng Mountain, producing cinnabar, mercury, and other minerals.", "Also there is Xinkeng Mountain, which produces cinnabar, mercury, and other minerals."),
"s1392": ("To the southwest is the Tongren Great River; to the northwest the Xiao River flows together with it; its lower course enters Yuan Prefecture territory and empties into the Yuan River.", "To the southwest is the Tongren Great River; to the northwest the Xiao River joins it; its lower course enters Yuan Prefecture territory and empties into the Yuan River."),
"s1393": ("The Shengxi Native Official Office, west of the prefecture seat.", "The Shengxi Native Official Office lies west of the prefecture seat."),
"s1394": ("In the Yuan the Shengxi Dam and Other Places Barbarian Native Official Office, subordinate to the Sizhou Pacification Office.", "In the Yuan it was the Shengxi Dam and Other Places Barbarian Native Official Office, subordinate to the Sizhou Pacification Office."),
"s1395": ("Renamed at the beginning of Hongwu, subordinate to the Sinan Pacification Commission.", "It was renamed at the beginning of the Hongwu reign and subordinated to the Sinan Pacification Commission."),
"s1396": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1397": ("To the west is Qiluo River, that is, Shengxi; it produces gold.", "To the west is Qiluo River — that is, Shengxi — which produces gold."),
"s1398": ("The Tixi Native Official Office, west of the prefecture seat.", "The Tixi Native Official Office lies west of the prefecture seat."),
"s1399": ("In the Yuan the Tixi and Other Places Military-Civil Native Official Office, subordinate to the Sizhou Pacification Office.", "In the Yuan it was the Tixi and Other Places Military-Civil Native Official Office, subordinate to the Sizhou Pacification Office."),
"s1400": ("Renamed at the beginning of Hongwu, subordinate to the Sinan Pacification Commission.", "It was renamed at the beginning of the Hongwu reign and subordinated to the Sinan Pacification Commission."),
}

out = {k: {"literal": v[0], "idiomatic": v[1]} for k, v in T.items()}
with open("scripts/mingshi046-batch12.json", "w") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
    f.write("\n")
print(f"Wrote {len(out)} entries")
