#!/usr/bin/env python3
import json

T = {
"s1401": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1402": ("To the east is the Yin River.", "To the east is the Yin River."),
"s1403": ("To the west is Tixi; it produces placer gold.", "To the west is Tixi, which produces placer gold."),
"s1404": ("The Dawanshan Native Official Office, south of the prefecture seat.", "The Dawanshan Native Official Office lies south of the prefecture seat."),
"s1405": ("In the Yuan the Dawanshan Suge Office and Other Places Military-Civil Native Official Office, subordinate to the Sizhou Pacification Office.", "In the Yuan it was the Dawanshan Suge Office and Other Places Military-Civil Native Official Office, subordinate to the Sizhou Pacification Office."),
"s1406": ("Renamed at the beginning of Hongwu, subordinate to the Sinan Pacification Commission.", "It was renamed at the beginning of the Hongwu reign and subordinated to the Sinan Pacification Commission."),
"s1407": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1408": ("The Wuluo Native Official Office, west of the prefecture seat.", "The Wuluo Native Official Office lies west of the prefecture seat."),
"s1409": ("In the Yuan the Wuluo Longqian and Other Places Native Official Office, subordinate to the Sizhou Pacification Office.", "In the Yuan it was the Wuluo Longqian and Other Places Native Official Office, subordinate to the Sizhou Pacification Office."),
"s1410": ("Renamed at the beginning of Hongwu, subordinate to the Sinan Pacification Commission.", "It was renamed at the beginning of the Hongwu reign and subordinated to the Sinan Pacification Commission."),
"s1411": ("In the second month of Yongle 11 Wuluo Prefecture was established, administering the Langxi Barbarian Native Official Office; the Wuluo, Dayi, Zhigu, and Pingtou Zhuoke native official offices were administered here.", "In the second month of Yongle 11 Wuluo Prefecture was established, administering the Langxi Barbarian Native Official Office; the Wuluo, Dayi, Zhigu, and Pingtou Zhuoke native official offices were administered here."),
"s1412": ("In the fifth month of Zhengtong 3 the prefecture was abolished and it came under jurisdiction.", "In the fifth month of Zhengtong 3 the prefecture was abolished and it came under Tongren Prefecture."),
"s1413": ("To the west is Jiulong Mountain; the Tongren Great River originates here.", "To the west is Jiulong Mountain; the Tongren Great River originates here."),
"s1414": ("Also to the southwest is Guanyin Tun, also called Wuluo Cave.", "Also to the southwest is Guanyin Tun, also called Wuluo Cave."),
"s1415": ("To the south is the Jiujiang River.", "To the south is the Jiujiang River."),
"s1416": ("Also there is Mu'er Stream, also called the Ninety-Nine Streams; its lower course also enters the Yuan River.", "Also there is Mu'er Stream, also called the Ninety-Nine Streams; its lower course also enters the Yuan River."),
"s1417": ("The Pingtou Zhuoke Native Official Office, northwest of the prefecture seat.", "The Pingtou Zhuoke Native Official Office lies northwest of the prefecture seat."),
"s1418": ("In the Yuan the Pingtou Zhuoke Tongda and Other Places Native Official Office, subordinate to the Sizhou Pacification Office.", "In the Yuan it was the Pingtou Zhuoke Tongda and Other Places Native Official Office, subordinate to the Sizhou Pacification Office."),
"s1419": ("Re-established in the tenth month of Hongwu 7, subordinate to the Sinan Pacification Commission.", "It was re-established in the tenth month of Hongwu 7 and subordinated to the Sinan Pacification Commission."),
"s1420": ("In the third month of Yongle 12 it belonged to Wuluo Prefecture; when the prefecture was abolished it came under jurisdiction.", "In the third month of Yongle 12 it came under Wuluo Prefecture; when that prefecture was abolished it came under Tongren Prefecture."),
"s1421": ("Also there are the Dayi Native Official Office and the Zhigu Stockade Native Official Office, both established in the seventh month of Yongle 3, subordinate to the Guizhou Pacification Commission; in the third month of Yongle 12 they were changed to Wuluo Prefecture; in the fifth month of Zhengtong 3 both were abolished together with the prefecture.", "Also there are the Dayi Native Official Office and the Zhigu Stockade Native Official Office, both established in the seventh month of Yongle 3 and subordinate to the Guizhou Pacification Commission; in the third month of Yongle 12 they were transferred to Wuluo Prefecture; in the fifth month of Zhengtong 3 both were abolished together with the prefecture."),
"s1422": ("Shiqian Prefecture was formerly territory of the Sizhou Pacification Commission.", "Shiqian Prefecture was originally territory of the Sizhou Pacification Commission."),
"s1423": ("In the second month of Yongle 11 Shiqian Prefecture was established.", "In the second month of Yongle 11 Shiqian Prefecture was established."),
"s1424": ("It administers one county and three native official offices.", "It administers one county and three native official offices."),
"s1425": ("Six hundred thirty li southwest from the provincial administration commission.", "It lies six hundred thirty li southwest of the provincial administration commission."),
"s1426": ("The Shiqian Native Official Office, attached.", "The Shiqian Native Official Office (seat-attached)."),
"s1427": ("In the Yuan the Shiqian and Other Places Military-Civil Native Official Office, subordinate to the Sizhou Pacification Office.", "In the Yuan it was the Shiqian and Other Places Military-Civil Native Official Office, subordinate to the Sizhou Pacification Office."),
"s1428": ("Re-established at the beginning of Hongwu, subordinate to the Sizhou Pacification Commission.", "It was re-established at the beginning of the Hongwu reign and subordinated to the Sizhou Pacification Commission."),
"s1429": ("In the third month of Yongle 12 it became the seat of Shiqian Prefecture.", "In the third month of Yongle 12 it became the seat of Shiqian Prefecture."),
"s1430": ("To the west is Yamen Mountain.", "To the west is Yamen Mountain."),
"s1431": ("To the south is Qiuman Cave.", "To the south is Qiuman Cave."),
"s1432": ("To the west is the Wu River, entering from Zunyi Prefecture in Sichuan and flowing northeast into Sinan Prefecture territory.", "To the west is the Wu River, which enters from Zunyi Prefecture in Sichuan and flows northeast into Sinan Prefecture territory."),
"s1433": ("There is the Shiqian River, flowing down into the Wu River.", "There is the Shiqian River, which flows down into the Wu River."),
"s1434": ("Longquan, west of the prefecture seat.", "Longquan lies west of the prefecture seat."),
"s1435": ("Formerly the Longquanping Native Official Office; in the Yuan it was the seat of the Sizhou Pacification Office.", "It was formerly the Longquanping Native Official Office; in the Yuan it was the seat of the Sizhou Pacification Office."),
"s1436": ("Re-established in the seventh month of Hongwu 7, subordinate to the Sizhou Pacification Commission.", "It was re-established in the seventh month of Hongwu 7 and subordinated to the Sizhou Pacification Commission."),
"s1437": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1438": ("In the fourth month of Wanli 29 it was changed to a county.", "In the fourth month of Wanli 29 it was changed to a county."),
"s1439": ("To the north is Tengyun Cave.", "To the north is Tengyun Cave."),
"s1440": ("To the south are Dengkan and other stockades.", "To the south are Dengkan and other stockades."),
"s1441": ("The Miaomin Native Official Office, southwest of the prefecture seat.", "The Miaomin Native Official Office lies southwest of the prefecture seat."),
"s1442": ("Established in the tenth month of Hongwu 7, subordinate to the Sizhou Pacification Commission.", "It was established in the tenth month of Hongwu 7 and subordinated to the Sizhou Pacification Commission."),
"s1443": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1444": ("The Gezhang Geshang Native Official Office, south of the prefecture seat.", "The Gezhang Geshang Native Official Office lies south of the prefecture seat."),
"s1445": ("In the Yuan subordinate to the Sizhou Pacification Office.", "In the Yuan it was subordinate to the Sizhou Pacification Office."),
"s1446": ("In the Hongwu period subordinate to the Sizhou Pacification Commission.", "During the Hongwu period it was subordinate to the Sizhou Pacification Commission."),
"s1447": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1448": ("The Longli Guard Military-Civil Command was established as a guard in the fourth month of Hongwu 23.", "Longli Guard was established in the fourth month of Hongwu 23."),
"s1449": ("In the fourth month of Hongwu 29 it was promoted to a military-civil command.", "In the fourth month of Hongwu 29 it was promoted to a military-civil command."),
"s1450": ("To the west is Lianhua Jing; also there is Jiaya River, flowing down into the Wengshou River.", "To the west is Lianhua Jing; also there is Jiaya River, which flows down into the Wengshou River."),
"s1451": ("To the southeast is the Pingfa Native Official Office, formerly the Yuan Pingfa and Other Places Native Official Office; re-established in Hongwu 15, subordinate to Guizhou Guard; in Hongwu 28 subordinate to Longli Guard; in the second month of Wanli 14 abolished and merged into Xingui County.", "To the southeast is the Pingfa Native Official Office, formerly the Yuan Pingfa and Other Places Native Official Office; it was re-established in Hongwu 15 and subordinated to Guizhou Guard; in Hongwu 28 it came under Longli Guard; in the second month of Wanli 14 it was abolished and merged into Xingui County."),
"s1452": ("Also to the west is Changchong Pass.", "Also to the west is Changchong Pass."),
"s1453": ("To the east is Longsong Pass.", "To the east is Longsong Pass."),
"s1454": ("It administers one native official office.", "It administers one native official office."),
"s1455": ("Fifty li west from the provincial administration commission.", "It lies fifty li west of the provincial administration commission."),
"s1456": ("The Taipingfa Native Official Office, south of the guard.", "The Taipingfa Native Official Office lies south of the guard."),
"s1457": ("Established in Hongwu 19, subordinate to Guizhou Guard.", "It was established in Hongwu 19 and subordinated to Guizhou Guard."),
"s1458": ("In Hongwu 28 it came under jurisdiction.", "In Hongwu 28 it came under Longli Guard."),
"s1459": ("To the northeast is Guxia Mountain.", "To the northeast is Guxia Mountain."),
"s1460": ("To the southeast is the Wengshou River, flowing down to join the Qingshui River.", "To the southeast is the Wengshou River, which flows down to join the Qingshui River."),
"s1461": ("The Xintian Guard Military-Civil Command was the Yuan Xintian Geman Pacification Office; later abolished.", "Xintian Guard was the Yuan Xintian Geman Pacification Office; it was later abolished."),
"s1462": ("In Hongwu 22 the Xintian thousand-household seat was established, subordinate to Guizhou Guard.", "In Hongwu 22 the Xintian thousand-household seat was established and subordinated to Guizhou Guard."),
"s1463": ("In the second month of Hongwu 23 it was changed to Xintian Guard, subordinate to the Guizhou regional command.", "In the second month of Hongwu 23 it was changed to Xintian Guard and subordinated to the Guizhou regional command."),
"s1464": ("In the fourth month of Hongwu 29 it was promoted to a military-civil command.", "In the fourth month of Hongwu 29 it was promoted to a military-civil command."),
"s1465": ("It administers five native official offices.", "It administers five native official offices."),
"s1466": ("One hundred ten li west from the provincial administration commission.", "It lies one hundred ten li west of the provincial administration commission."),
"s1467": ("The Xintian Native Official Office, attached.", "The Xintian Native Official Office (seat-attached)."),
"s1468": ("Established in Hongwu 4.", "It was established in Hongwu 4."),
"s1469": ("To the east is Pingxu Cave, also called Zhumu Cave.", "To the east is Pingxu Cave, also called Zhumu Cave."),
"s1470": ("To the northwest is the Qingshui River.", "To the northwest is the Qingshui River."),
"s1471": ("To the southwest is the Wengcheng River; there is the Wengcheng River native pacification sub-office.", "To the southwest is the Wengcheng River; there is the Wengcheng River native pacification sub-office."),
"s1472": ("Also to the east is Gumang Pass.", "Also to the east is Gumang Pass."),
"s1473": ("The Xiaopingfa Native Official Office, southwest of the guard.", "The Xiaopingfa Native Official Office lies southwest of the guard."),
"s1474": ("Established in the sixth month of Hongwu 15, subordinate to Guizhou Guard; soon subordinate to Longli Guard.", "It was established in the sixth month of Hongwu 15 and subordinated to Guizhou Guard; soon afterward it came under Longli Guard."),
"s1475": ("In Hongwu 29 it came under jurisdiction.", "In Hongwu 29 it came under Xintian Guard."),
"s1476": ("The Baping Stockade Native Official Office, south of the guard.", "The Baping Stockade Native Official Office lies south of the guard."),
"s1477": ("Established in the sixth month of Hongwu 15, subordinate to Guizhou Guard; soon subordinate to Longli Guard.", "It was established in the sixth month of Hongwu 15 and subordinated to Guizhou Guard; soon afterward it came under Longli Guard."),
"s1478": ("In Hongwu 29 it came under jurisdiction.", "In Hongwu 29 it came under Xintian Guard."),
"s1479": ("The Danping Native Official Office, southwest of the guard.", "The Danping Native Official Office lies southwest of the guard."),
"s1480": ("Established in Hongwu 30; soon abolished.", "It was established in Hongwu 30 and was soon abolished."),
"s1481": ("Re-established in Yongle 2.", "It was re-established in Yongle 2."),
"s1482": ("The Danxing Native Official Office, southwest of the guard.", "The Danxing Native Official Office lies southwest of the guard."),
"s1483": ("Established in Hongwu 30; soon abolished.", "It was established in Hongwu 30 and was soon abolished."),
"s1484": ("Re-established in Yongle 2.", "It was re-established in Yongle 2."),
"s1485": ("Annan Guard: in the first month of Hongwu 15 Weisa Guard was established here; soon abolished.", "Annan Guard: in the first month of Hongwu 15 Weisa Guard was established here and was soon abolished."),
"s1486": ("Re-established in the twelfth month of Hongwu 23 and renamed, subordinate to the Guizhou regional command.", "It was re-established in the twelfth month of Hongwu 23, renamed Annan Guard, and subordinated to the Guizhou regional command."),
"s1487": ("To the south is Weisa Mountain.", "To the south is Weisa Mountain."),
"s1488": ("To the east is Panjiang Mountain; there is Qingyuan Cave.", "To the east is Panjiang Mountain; there is Qingyuan Cave."),
"s1489": ("Also there is the North Pan River, entering from Zhanyi Prefecture in Yunnan and flowing south into Anshun Prefecture territory.", "Also there is the North Pan River, which enters from Zhanyi Prefecture in Yunnan and flows south into Anshun Prefecture territory."),
"s1490": ("To the southeast is the Zhebu River, entering from Pu'an Prefecture and emptying into the Pan River.", "To the southeast is the Zhebu River, which enters from Pu'an Prefecture and empties into the Pan River."),
"s1491": ("To the west is Jiangxi Po; initially a stockade garrison was established here; soon moved to Weisa and a city was built as a guard.", "To the west is Jiangxi Po; initially a stockade garrison was established here; soon it was moved to Weisa and a city was built as a guard."),
"s1492": ("To the south is Wuming Pass, also established in the Hongwu period.", "To the south is Wuming Pass, also established during the Hongwu period."),
"s1493": ("Three hundred forty li northeast from the provincial administration commission.", "It lies three hundred forty li northeast of the provincial administration commission."),
"s1494": ("Weiqing Guard was established in the sixth month of Hongwu 23, subordinate to the Guizhou regional command.", "Weiqing Guard was established in the sixth month of Hongwu 23 and subordinated to the Guizhou regional command."),
"s1495": ("To the north is Yang'er Mountain.", "To the north is Yang'er Mountain."),
"s1496": ("To the west is the Deicheng River, that is, the upper course of the Luguang River.", "To the west is the Deicheng River — that is, the upper course of the Luguang River."),
"s1497": ("To the northwest is the Yachi River, that is, the Wu River.", "To the northwest is the Yachi River — that is, the Wu River."),
"s1498": ("Sixty li west from the provincial administration commission.", "It lies sixty li west of the provincial administration commission."),
"s1499": ("Pingba Guard was established in the intercalary fourth month of Hongwu 23, subordinate to the Guizhou regional command.", "Pingba Guard was established in the intercalary fourth month of Hongwu 23 and subordinated to the Guizhou regional command."),
"s1500": ("To the southeast is Nanxian Cave; there is Matou Mountain.", "To the southeast is Nanxian Cave; there is Matou Mountain."),
}

out = {k: {"literal": v[0], "idiomatic": v[1]} for k, v in T.items()}
with open("scripts/mingshi046-batch13.json", "w") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
    f.write("\n")
print(f"Wrote {len(out)} entries")
