#!/usr/bin/env python3
import json

T = {
"s1201": ("Sixty li southwest from the prefecture seat.", "It lies sixty li southwest of the prefecture seat."),
"s1202": ("Xinglong Guard was established in the sixth month of Hongwu 22, subordinate to the Guizhou regional command.", "Xinglong Guard was established in the sixth month of Hongwu 22 and subordinated to the Guizhou regional command."),
"s1203": ("In Wanli 29 it came under jurisdiction.", "In Wanli 29 it came under the prefecture's jurisdiction."),
"s1204": ("To the north is Longyan Mountain, also called Longdong Mountain.", "To the north is Longyan Mountain, also known as Longdong Mountain."),
"s1205": ("Also there is Jiedong Cave, deep and perilous.", "There is also Jiedong Cave, deep and perilous."),
"s1206": ("To the east is Feiyun Cliff.", "To the east is Feiyun Cliff."),
"s1207": ("One hundred twenty li southwest from the prefecture seat.", "It lies one hundred twenty li southwest of the prefecture seat."),
"s1208": ("Huangping Prefecture was formerly the Huangping Pacification Office.", "Huangping Prefecture was originally the Huangping Pacification Office."),
"s1209": ("Established in the eleventh month of Hongwu 7, subordinate to the Bozhou Pacification Commission.", "It was established in the eleventh month of Hongwu 7, subordinate to the Bozhou Pacification Commission."),
"s1210": ("In the fourth month of Wanli 29 it was changed to a prefecture and came under jurisdiction.", "In the fourth month of Wanli 29 it was changed to a prefecture and subordinated to the prefecture."),
"s1211": ("To the east is Qili Valley.", "To the east is Qili Valley."),
"s1212": ("To the southwest is Liangcha River, named for the confluence of two sources.", "To the southwest is Liangcha River, named because two streams join there."),
"s1213": ("Also to the east is Lengshui River.", "Also to the east is Lengshui River."),
"s1214": ("To the northwest is the Huangping defensive battalion thousand-household seat, established in the first month of Hongwu 11; in the first month of Hongwu 15 it was changed to a guard, and in the intercalary second month it reverted to a thousand-household seat.", "To the northwest is the Huangping defensive battalion thousand-household seat, established in the first month of Hongwu 11; in the first month of Hongwu 15 it was promoted to a guard, and in the intercalary second month it reverted to a thousand-household seat."),
"s1215": ("Thirty li south from the prefecture seat.", "It lies thirty li south of the prefecture seat."),
"s1216": ("Yuqing, west.", "Yuqing lies to the west."),
"s1217": ("Formerly the Yuqing Native Official Office, established in Hongwu 17, subordinate to the Bozhou Pacification Commission.", "It was formerly the Yuqing Native Official Office, established in Hongwu 17 and subordinate to the Bozhou Pacification Commission."),
"s1218": ("In the sixth month of Wanli 29 it was changed to a county and came under jurisdiction.", "In the sixth month of Wanli 29 it was changed to a county and subordinated to the prefecture."),
"s1219": ("To the east is the Baimi Native Official Office, also established in Hongwu 17, subordinate to the Bozhou Pacification Guard Commission; in the fourth month of Wanli 29 it was abolished and merged into Yuqing County.", "To the east is the Baimi Native Official Office, also established in Hongwu 17 and subordinate to the Bozhou Pacification Guard Commission; in the fourth month of Wanli 29 it was abolished and merged into Yuqing County."),
"s1220": ("To the south is the Xiao Wu River, flowing down into the Wu River.", "To the south is the Xiao Wu River, which flows down into the Wu River."),
"s1221": ("To the southeast is the Baimi River, flowing down to join the Sinan River.", "To the southeast is the Baimi River, whose lower course joins the Sinan River."),
"s1222": ("Also there is Zoumaping Stockade, established in Jiajing 34.", "There is also Zoumaping Stockade, established in Jiajing 34."),
"s1223": ("Weng'an, northwest.", "Weng'an lies to the northwest."),
"s1224": ("Formerly the Wengshui Pacification Office, established at the beginning of Hongwu.", "It was formerly the Wengshui Pacification Office, established at the beginning of the Hongwu reign."),
"s1225": ("In the fourth month of Wanli 29 it was changed to a county and came under jurisdiction.", "In the fourth month of Wanli 29 it was changed to a county and subordinated to the prefecture."),
"s1226": ("To the east is the Caotang Pacification Office, established in the sixth month of Hongwu 17; also there is the Chong'an Native Official Office, established in the ninth month of Yongle 4 — both subordinate to the Bozhou Pacification Commission; in the fourth month of Wanli 29 both were abolished and merged into Weng'an County.", "To the east is the Caotang Pacification Office, established in the sixth month of Hongwu 17; also there is the Chong'an Native Official Office, established in the ninth month of Yongle 4 — both subordinate to the Bozhou Pacification Commission; in the fourth month of Wanli 29 both were abolished and merged into Weng'an County."),
"s1227": ("To the southeast is Wanzhang Mountain.", "To the southeast is Wanzhang Mountain."),
"s1228": ("To the west is the Wu River; all mountain streams within the county flow together into it.", "To the west is the Wu River, into which all mountain streams within the county flow."),
"s1229": ("Also there is Huangtan Pass.", "There is also Huangtan Pass."),
"s1230": ("To the northeast is Feilian Fort; there is Tianbang Tun; to the west are Xiping and other stockades.", "To the northeast is Feilian Fort; there is Tianbang Tun; to the west are Xiping and other stockades."),
"s1231": ("Meitan, north.", "Meitan lies to the north."),
"s1232": ("In the fourth month of Wanli 29 it was established from Bozhou Meitan territory.", "In the fourth month of Wanli 29 it was established from Bozhou Meitan territory."),
"s1233": ("To the west is the Rongshan Native Official Office, established in the Hongwu period, subordinate to the Bozhou Pacification Commission.", "To the west is the Rongshan Native Official Office, established during the Hongwu period and subordinate to the Bozhou Pacification Commission."),
"s1234": ("In Wanli 29 it was abolished and merged into Meitan County.", "In Wanli 29 it was abolished and merged into Meitan County."),
"s1235": ("To the south is the Meitan River; also to the west is the Sanjiang River; both flow down into the Wu River.", "To the south is the Meitan River; also to the west is the Sanjiang River; both flow down into the Wu River."),
"s1236": ("The Kaili Native Official Office, northeast of the prefecture seat.", "The Kaili Native Official Office lies northeast of the prefecture seat."),
"s1237": ("Formerly the Kaili Pacification Office, established in the second month of Jiajing 8 from Bozhou Pacification Commission territory, subordinate to Qingping Guard.", "It was formerly the Kaili Pacification Office, established in the second month of Jiajing 8 from Bozhou Pacification Commission territory and subordinate to Qingping Guard."),
"s1238": ("In Wanli 29 it came under jurisdiction.", "In Wanli 29 it came under the prefecture's jurisdiction."),
"s1239": ("In the sixth month of year 35 it was changed to a native official office.", "In the sixth month of Wanli 35 it was changed to a native official office."),
"s1240": ("The Yangyi Native Official Office, southeast of the prefecture seat.", "The Yangyi Native Official Office lies southeast of the prefecture seat."),
"s1241": ("Established at the beginning of Hongwu, subordinate to Pingyue Guard.", "It was established at the beginning of the Hongwu reign and subordinated to Pingyue Guard."),
"s1242": ("In Wanli 29 it belonged to the prefecture.", "In Wanli 29 it came under the prefecture."),
"s1243": ("To the west is Shanmuqing Mountain.", "To the west is Shanmuqing Mountain."),
"s1244": ("Also there is the Qingshui River; its upper course enters from Xintian Guard, passes west of the city, also called Pilong River; northward it passes through the Miao territories of Guaixi and Baxiang and enters the Wu River.", "Also there is the Qingshui River; its upper course enters from Xintian Guard and passes west of the city — also called Pilong River; northward it passes through the Miao territories of Guaixi and Baxiang and enters the Wu River."),
"s1245": ("Liping Prefecture was formerly territory of the Sizhou Pacification Commission.", "Liping Prefecture was originally territory of the Sizhou Pacification Commission."),
"s1246": ("In the first month of Hongwu 18 Wukai Guard was established, subordinate to the Huguang regional command; later abolished.", "In the first month of Hongwu 18 Wukai Guard was established, subordinate to the Huguang regional command, and was later abolished."),
"s1247": ("In the eleventh month of year 35 it was re-established.", "In the eleventh month of Hongwu 35 it was re-established."),
"s1248": ("In the second month of Yongle 11 Liping Prefecture was established at the guard city, subordinate to the Guizhou Provincial Administration Commission.", "In the second month of Yongle 11 Liping Prefecture was established at the guard city and subordinated to the Guizhou Provincial Administration Commission."),
"s1249": ("In Hongzhi 10 the prefectural seat was moved south of the guard.", "In Hongzhi 10 the prefectural seat was moved south of the guard."),
"s1250": ("In the eleventh month of Wanli 29 the prefecture was changed to belong to Huguang.", "In the eleventh month of Wanli 29 the prefecture was transferred to Huguang."),
"s1251": ("In the fourth month of year 31 it returned to Guizhou.", "In the fourth month of Wanli 31 it returned to Guizhou."),
"s1252": ("To the south is Baodai Mountain.", "To the south is Baodai Mountain."),
"s1253": ("To the east is Motian Ridge.", "To the east is Motian Ridge."),
"s1254": ("To the northeast is Tonggu Cliff.", "To the northeast is Tonggu Cliff."),
"s1255": ("To the west is the Xinhua River.", "To the west is the Xinhua River."),
"s1256": ("Also there is the Fulu River; its upper source is the Guzhou River, and its lower course enters Huaiyuan County in Guangxi.", "Also there is the Fulu River; its upper source is the Guzhou River, and its lower course enters Huaiyuan County in Guangxi."),
"s1257": ("To the southwest is the Liping defensive battalion thousand-household seat, established in the ninth month of Hongwu 21, subordinate to Wukai Guard.", "To the southwest is the Liping defensive battalion thousand-household seat, established in the ninth month of Hongwu 21 and subordinate to Wukai Guard."),
"s1258": ("It administers one county and thirteen native official offices.", "It administers one county and thirteen native official offices."),
"s1259": ("Six hundred thirty li west from the provincial administration commission.", "It lies six hundred thirty li west of the provincial administration commission."),
"s1260": ("The Zhonglin Yandong Barbarian Native Official Office, north of the prefecture seat.", "The Zhonglin Yandong Barbarian Native Official Office lies north of the prefecture seat."),
"s1261": ("Established at the beginning of Hongwu, later abolished.", "It was established at the beginning of the Hongwu reign and was later abolished."),
"s1262": ("In the first month of Yongle 1 it was re-established.", "In the first month of Yongle 1 it was re-established."),
"s1263": ("In the third month of year 12 it belonged to Xinhua Prefecture; when the prefecture was abolished it came under jurisdiction.", "In the third month of Yongle 12 it belonged to Xinhua Prefecture; when that prefecture was abolished it came under Liping Prefecture."),
"s1264": ("The two offices below follow this pattern.", "The two offices below follow this pattern."),
"s1265": ("The Chixi Nandong Barbarian Native Official Office, northeast of the prefecture seat.", "The Chixi Nandong Barbarian Native Official Office lies northeast of the prefecture seat."),
"s1266": ("The Longli Barbarian Native Official Office, north of the prefecture seat.", "The Longli Barbarian Native Official Office lies north of the prefecture seat."),
"s1267": ("To the south is the Longli defensive battalion thousand-household seat, established in Hongwu 25, subordinate to Wukai Guard.", "To the south is the Longli defensive battalion thousand-household seat, established in Hongwu 25 and subordinate to Wukai Guard."),
"s1268": ("Sinan Prefecture was the Yuan Sinan Pacification Commission, subordinate to the Huguang Branch Secretariat.", "Sinan Prefecture was the Yuan Sinan Pacification Commission, subordinate to the Huguang Branch Secretariat."),
"s1269": ("In Hongwu 4 it was changed to belong to Sichuan.", "In Hongwu 4 it was transferred to Sichuan."),
"s1270": ("In the twelfth month of Hongwu 6 it was promoted to the Sinan Circuit Pacification Commission, still subordinate to Huguang.", "In the twelfth month of Hongwu 6 it was promoted to the Sinan Circuit Pacification Commission, still subordinate to Huguang."),
"s1271": ("In the second month of Yongle 11 it was changed to a prefecture, subordinate to the Guizhou Provincial Administration Commission.", "In the second month of Yongle 11 it was changed to a prefecture and subordinated to the Guizhou Provincial Administration Commission."),
"s1272": ("In the third month of Longqing 4 the seat was moved to Pingxi Guard.", "In the third month of Longqing 4 the seat was moved to Pingxi Guard."),
"s1273": ("Soon it returned to the former location.", "Soon afterward it returned to its former location."),
"s1274": ("There are the Duru, Wubao, Erkeng, and other pacification sub-offices.", "There are the Duru, Wubao, Erkeng, and other pacification sub-offices."),
"s1275": ("Also there is the Tanhan Pianli Water-and-Soil Pacification Sub-Office.", "Also there is the Tanhan Pianli water-and-soil pacification sub-office."),
"s1276": ("Also there is the Banqiao Pacification Sub-Office, formerly subordinate to Shiqian Prefecture; later it came under jurisdiction.", "Also there is the Banqiao pacification sub-office, formerly subordinate to Shiqian Prefecture and later transferred here."),
"s1277": ("It administers three counties and three native official offices.", "It administers three counties and three native official offices."),
"s1278": ("Six hundred twenty li southwest from the provincial administration commission.", "It lies six hundred twenty li southwest of the provincial administration commission."),
"s1279": ("Anhua, attached.", "Anhua (seat-attached county)."),
"s1280": ("Formerly the Shuijijiang Native Official Office, in the Yuan subordinate to the Sizhou Pacification Office.", "It was formerly the Shuijijiang Native Official Office, subordinate in the Yuan to the Sizhou Pacification Office."),
"s1281": ("At the beginning of Hongwu it was renamed Shuide River and subordinated to the Sinan Pacification Commission.", "At the beginning of the Hongwu reign it was renamed Shuide River and subordinated to the Sinan Pacification Commission."),
"s1282": ("In the third month of Yongle 12 it belonged to the prefecture.", "In the third month of Yongle 12 it came under the prefecture."),
"s1283": ("In Wanli 33 Anhua County was established in its place.", "In Wanli 33 Anhua County was established in its place."),
"s1284": ("To the southwest is Yamen Mountain.", "To the southwest is Yamen Mountain."),
"s1285": ("To the south is Wansheng Mountain.", "To the south is Wansheng Mountain."),
"s1286": ("Also there is the Wu River, entering from Shiqian Prefecture, passing north of the city at Nianyu Gorge, entering Pengshui County in Sichuan, and joining the Fuling River.", "Also there is the Wu River, which enters from Shiqian Prefecture, passes north of the city at Nianyu Gorge, enters Pengshui County in Sichuan, and joins the Fuling River."),
"s1287": ("To the southeast is the Shuide River, a branch of the Wu River; also the Siyin River flows together with it, and its lower course also enters the Fuling River.", "To the southeast is the Shuide River, a branch of the Wu River; the Siyin River also flows into it, and its lower course likewise enters the Fuling River."),
"s1288": ("Formerly there were the Hong'an and Huaji native official offices, subordinate to the Sinan Pacification Commission; abolished in the fifth month of Hongwu 26.", "Formerly there were the Hong'an and Huaji native official offices, subordinate to the Sinan Pacification Commission; they were abolished in the fifth month of Hongwu 26."),
"s1289": ("To the east is Shuisheng Pass.", "To the east is Shuisheng Pass."),
"s1290": ("To the south is Wusheng Pass.", "To the south is Wusheng Pass."),
"s1291": ("To the north is Taiping Pass.", "To the north is Taiping Pass."),
"s1292": ("The Manyi Native Official Office, attached.", "The Manyi Native Official Office (seat-attached)."),
"s1293": ("Established in the tenth month of Hongwu 10, subordinate to the Sinan Pacification Commission.", "It was established in the tenth month of Hongwu 10 and subordinated to the Sinan Pacification Commission."),
"s1294": ("In the third month of Yongle 12 it belonged to the prefecture.", "In the third month of Yongle 12 it came under the prefecture."),
"s1295": ("Wuchuan, north of the prefecture seat.", "Wuchuan lies north of the prefecture seat."),
"s1296": ("In the Yuan subordinate to the Sizhou Pacification Office.", "In the Yuan it was subordinate to the Sizhou Pacification Office."),
"s1297": ("In Hongwu 5 it belonged to Zhenyuan Prefecture.", "In Hongwu 5 it belonged to Zhenyuan Prefecture."),
"s1298": ("After year 17 it again belonged to Sizhou.", "After Hongwu 17 it again belonged to Sizhou."),
"s1299": ("In the third month of Yongle 12 it came under jurisdiction.", "In the third month of Yongle 12 it came under the prefecture."),
"s1300": ("To the east is the Hezhi River; also there is the Luoduo River; both flow down into the Shuide River.", "To the east is the Hezhi River; also there is the Luoduo River; both flow down into the Shuide River."),
}

out = {k: {"literal": v[0], "idiomatic": v[1]} for k, v in T.items()}
with open("scripts/mingshi046-batch11.json", "w") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
    f.write("\n")
print(f"Wrote {len(out)} entries")
