/** liaoshi 038 s0101–s0150 */
export const T = {
  s0101: [
    'Originally stockade land; Goryeo made it Longyuan County; Bohai kept it; Liao at first abolished it.',
    'Originally a stockade site; Goryeo made Longyuan County; Bohai retained it; early Liao abolished it.',
  ],
  s0102: [
    'Shengzong on the eastern campaign restored it under the army designation.',
    'Shengzong restored it on the eastern campaign, taking the army name.',
  ],
  s0103: ['Civilian households 1,000.', '1,000 civilian households.'],
  s0104: ['Yan Prefecture.', 'Yan Prefecture.'],
  s0105: [
    'Originally Bohai Longhe Commandery; former counties four: Haiyang, Jiehai, Gechuan, and Longhe—all abolished.',
    'Originally Bohai Longhe Commandery; four former counties—Haiyang, Jiehai, Gechuan, Longhe—all abolished.',
  ],
  s0106: ['Households 300.', '300 households.'],
  s0107: ['Subordinate to Kai Prefecture.', 'Under Kai Prefecture.'],
  s0108: ['One hundred forty li apart.', 'One hundred forty li distant.'],
  s0109: ['Mu Prefecture, Baohe Army, cishi.', 'Mu Prefecture (Baohe Army), cishi.'],
  s0110: [
    'Originally Bohai Huiyi Commandery; former counties four: Huiyi, Shuiqi, Shunhua, and Meixian—all abolished.',
    'Originally Bohai Huiyi Commandery; four former counties—Huiyi, Shuiqi, Shunhua, Meixian—all abolished.',
  ],
  s0111: ['Households 300.', '300 households.'],
  s0112: ['Subordinate to Kai Prefecture.', 'Under Kai Prefecture.'],
  s0113: ['One hundred twenty li northeast of Kai Prefecture.', 'Kai Prefecture lay one hundred twenty li to the northeast.'],
  s0114: ['Governing one county:', 'One county:'],
  s0115: ['Huiyi County.', 'Huiyi County.'],
  s0116: ['He Prefecture, cishi.', 'He Prefecture (cishi).'],
  s0117: [
    'Originally Bohai Jili Commandery; former counties four: Honghe, Songcheng, Jili, and Shishan—all abolished.',
    'Originally Bohai Jili Commandery; four former counties—Honghe, Songcheng, Jili, Shishan—all abolished.',
  ],
  s0118: ['Households 300.', '300 households.'],
  s0119: ['Subordinate to Kai Prefecture.', 'Under Kai Prefecture.'],
  s0120: ['Ding Prefecture, Bao\'ning Army.', 'Ding Prefecture (Bao\'ning Army).'],
  s0121: [
    'Goryeo established the prefecture; one former county called Dingdong.',
    'Goryeo founded the prefecture; one former county, Dingdong.',
  ],
  s0122: [
    'In Tonghe year 13 of Shengzong it was raised to an army; Liaoxi people were moved to fill it.',
    'Shengzong Tonghe year 13 raised it to an army and settled Liaoxi households there.',
  ],
  s0123: ['Subordinate to the Eastern Capital regent office.', 'Under the Eastern Capital regent office.'],
  s0124: ['Governing one county:', 'One county:'],
  s0125: ['Dingdong County.', 'Dingdong County.'],
  s0126: [
    'Established by Goryeo; Liao moved Liaoxi people to dwell there.',
    'Goryeo founded it; Liao relocated Liaoxi inhabitants there.',
  ],
  s0127: ['Households 800.', '800 households.'],
  s0128: ['Bao Prefecture, Xuanyi Army, military commissioner.', 'Bao Prefecture (Xuanyi Army), military commissioner.'],
  s0129: [
    'Goryeo established the prefecture; one former county called Laiyuan.',
    'Goryeo founded the prefecture; one former county, Laiyuan.',
  ],
  s0130: [
    'Because Goryeo King Xun had been installed without authorization and would not submit when questioned, at the end of Tonghe Goryeo surrendered; 7 in Kaitai year 3 Bao and Ding two prefectures were taken and a monopoly market was placed here.',
    'When Goryeo King Xun was irregularly enthroned and defied inquiry, Goryeo submitted at Tonghe\'s end; seventh: Kaitai year 3 seized Bao and Ding and opened a monopoly market here.',
  ],
  s0131: ['Subordinate to the Eastern Capital army command.', 'Under the Eastern Capital army command.'],
  s0132: ['Governing prefectures and armies two, counties one:', 'Two prefectures/armies, one county:'],
  s0133: ['Laiyuan County.', 'Laiyuan County.'],
  s0134: [
    'At first Liaoxi county people were moved to fill it; later seven hundred Xi and Han troops were moved to garrison.',
    'Liaoxi county populations were first relocated here; later seven hundred Xi and Han soldiers garrisoned it.',
  ],
  s0135: ['Households 1,000.', '1,000 households.'],
  s0136: ['Xuan Prefecture, Dingyuan Army, cishi.', 'Xuan Prefecture (Dingyuan Army), cishi.'],
  s0137: ['In Kaitai year 3 Han households were moved to establish it.', 'Kaitai year 3 settled Han households to found it.'],
  s0138: ['Subordinate to Bao Prefecture.', 'Under Bao Prefecture.'],
  s0139: ['Huaihua Army, lower, cishi.', 'Huaihua Army (lower rank), cishi.'],
  s0140: ['Established in Kaitai year 3.', 'Founded in Kaitai year 3.'],
  s0141: ['Subordinate to Bao Prefecture.', 'Under Bao Prefecture.'],
  s0142: ['Chen Prefecture, Fengguo Army, military commissioner.', 'Chen Prefecture (Fengguo Army), military commissioner.'],
  s0143: ['Originally Goryeo Gaimou Fort.', 'Originally Goryeo\'s Gaimou Fort.'],
  s0144: [
    'Tang Taizong with Li Shiji broke Gaimou Fort—this is that place.',
    'Tang Taizong and Li Shiji stormed Gaimou Fort here.',
  ],
  s0145: [
    'Bohai changed it to Gai Prefecture, then Chen Prefecture, named for Chenhan.',
    'Bohai renamed it Gai Prefecture, then Chen Prefecture after Chenhan.',
  ],
  s0146: [
    'Markets and lanes stood close together—it was the greatest thoroughfare.',
    'Its markets and lanes crowded together—the region\'s chief crossroads.',
  ],
  s0147: ['Liao moved its people to Zu Prefecture.', 'Liao relocated its populace to Zu Prefecture.'],
  s0148: ['At first called Changping Army.', 'Initially titled Changping Army.'],
  s0149: ['Households 2,000.', '2,000 households.'],
  s0150: ['Subordinate to the Eastern Capital regent office.', 'Under the Eastern Capital regent office.'],
};
