/** liaoshi 038 s0201–s0250 */
export const T = {
  s0201: ['Yao Prefecture, cishi.', 'Yao Prefecture (cishi).'],
  s0202: [
    'Originally Bohai Jiao Prefecture; former counties five: Jiaoshan, Diaoling, Siquan, Jianshan, and Yanyuan—all abolished.',
    'Originally Bohai Jiao Prefecture; five former counties—Jiaoshan, Diaoling, Siquan, Jianshan, Yanyuan—all abolished.',
  ],
  s0203: ['Households 700.', '700 households.'],
  s0204: ['Subordinate to Hai Prefecture.', 'Under Hai Prefecture.'],
  s0205: ['Two hundred li northeast of Hai Prefecture.', 'Hai Prefecture lay two hundred li to the northeast.'],
  s0206: ['Governing one county:', 'One county:'],
  s0207: ['Yanyuan County.', 'Yanyuan County.'],
  s0208: [
    'East borders Silla; the old Pyongyang city lies southwest of the county.',
    'It bordered Silla on the east; old Pyongyang lay southwest of the county.',
  ],
  s0209: ['One hundred twenty li northeast of Hai Prefecture.', 'One hundred twenty li northeast of Hai.'],
  s0210: ['Pin Prefecture, Rouyuan Army, cishi.', 'Pin Prefecture (Rouyuan Army), cishi.'],
  s0211: [
    'Originally Bohai Qing Prefecture; former counties five: Tianqing, Shenyang, Lianchi, Langshan, and Xianyan—all abolished.',
    'Originally Bohai Qing Prefecture; five former counties—Tianqing, Shenyang, Lianchi, Langshan, Xianyan—all abolished.',
  ],
  s0212: ['Households 500.', '500 households.'],
  s0213: ['Subordinate to Hai Prefecture.', 'Under Hai Prefecture.'],
  s0214: ['One hundred twenty li southeast of Hai Prefecture.', 'One hundred twenty li southeast of Hai.'],
  s0215: ['Lu Prefecture, Yalu Army, military commissioner.', 'Lu Prefecture (Yalu Army), military commissioner.'],
  s0216: [
    'Originally old Goryeo state; Bohai styled it Western Capital Yalu Prefecture.',
    'Originally core Goryeo territory; Bohai called it Western Capital Yalu Prefecture.',
  ],
  s0217: [
    'Walls three zhang high, twenty li in circuit; it superintended Shen, Huan, Feng, and Zheng four prefectures.',
    'Walls three zhang high, twenty li around; it oversaw Shen, Huan, Feng, and Zheng prefectures.',
  ],
  s0218: [
    'Former counties three: Shenlu, Shenhua, and Jianmen—all abolished.',
    'Three former counties—Shenlu, Shenhua, Jianmen—all abolished.',
  ],
  s0219: [
    'When Da Yanlin rebelled, remnant factions were moved to Shangjing and Yisu County established for them.',
    'Da Yanlin\'s rebellion sent survivors to Shangjing and founded Yisu County for them.',
  ],
  s0220: ['Those remaining: households 2,000.', '2,000 households remained.'],
  s0221: ['Subordinate to the Eastern Capital regent office.', 'Under the Eastern Capital regent office.'],
  s0222: ['Governing four prefectures and two counties:', 'Four prefectures, two counties:'],
  s0223: ['Hongwen County.', 'Hongwen County.'],
  s0224: ['Shenxiang County.', 'Shenxiang County.'],
  s0225: ['Huan Prefecture.', 'Huan Prefecture.'],
  s0226: [
    'Goryeo central capital city; former counties three: Huandu, Shenxiang, and Qi River—10 all abolished.',
    'Goryeo\'s central capital; three former counties—Huandu, Shenxiang, Qi River—tenth note: all abolished.',
  ],
  s0227: [
    'The Goryeo king here built palaces; the people called it the New State.',
    'A Goryeo king raised palaces here; subjects called it the New State.',
  ],
  s0228: [
    'Five generations later Zhao, at Jin Emperor Kangdi\'s Jianyuan opening, was defeated by Murong and the palaces burned.',
    'Five generations on, Zhao was crushed by Murong at Jin Kangdi\'s Jianyuan opening and the palaces burned.',
  ],
  s0229: ['Households 700.', '700 households.'],
  s0230: ['Subordinate to Lu Prefecture.', 'Under Lu Prefecture.'],
  s0231: ['Two hundred li southwest.', 'Two hundred li to the southwest.'],
  s0232: ['Feng Prefecture.', 'Feng Prefecture.'],
  s0233: [
    'Bohai established Pan\'an Commandery; former counties four: Anfeng, Boke, Xirang, and Xiashi—all abolished.',
    'Bohai\'s Pan\'an Commandery had four former counties—Anfeng, Boke, Xirang, Xiashi—all abolished.',
  ],
  s0234: ['Households 300.', '300 households.'],
  s0235: ['Subordinate to Lu Prefecture.', 'Under Lu Prefecture.'],
  s0236: ['Two hundred ten li northeast.', 'Two hundred ten li to the northeast.'],
  s0237: ['Zheng Prefecture.', 'Zheng Prefecture.'],
  s0238: [
    'Originally Beiru King\'s land; the state was annexed by Gongsun Kang.',
    'Originally the Beiru king\'s domain, later annexed by Gongsun Kang.',
  ],
  s0239: ['Bohai established Beiru Commandery.', 'Bohai founded Beiru Commandery.'],
  s0240: ['There was the Beiru River.', 'The Beiru River ran through it.'],
  s0241: ['Households 500.', '500 households.'],
  s0242: ['Subordinate to Lu Prefecture.', 'Under Lu Prefecture.'],
  s0243: ['Three hundred eighty li northwest.', 'Three hundred eighty li to the northwest.'],
  s0244: ['Governing one county:', 'One county:'],
  s0245: ['Dongna County.', 'Dongna County.'],
  s0246: ['Originally Han Dongnai County land.', 'Originally Han Dongnai County territory.'],
  s0247: ['11 Seventy li west of the prefecture.', 'Eleventh note: seventy li west of the prefecture.'],
  s0248: ['Mu Prefecture.', 'Mu Prefecture.'],
  s0249: [
    'Originally Bohai Anyuan Prefecture land; former counties two: Muhua and Chongping—long abolished.',
    'Originally Bohai Anyuan Prefecture; two former counties—Muhua, Chongping—long abolished.',
  ],
  s0250: ['Households 200.', '200 households.'],
};
