/** liaoshi 038 s0451–s0500 */
export const T = {
  s0451: [
    'Shengzong, because the land bordered Goryeo, in the opening of Kaitai established the prefecture and filled it with captured Han people.',
    'Bordering Goryeo, Shengzong founded it at Kaitai\'s opening with Han captives.',
  ],
  s0452: [
    'Military affairs belonged to the Huanglong Prefecture Deployment Office.',
    'Military affairs to Huanglong Prefecture Deployment Office.',
  ],
  s0453: ['Governing three prefectures, details unclear;', 'Three subordinate prefectures (details unclear);'],
  s0454: ['counties two:', 'two counties:'],
  s0455: ['Wuchang County.', 'Wuchang County.'],
  s0456: [
    'Originally Bohai Huaifu County land; carved out from Ping Prefecture Intendant Office and Baoshan County one thousand households to subordinate it.',
    'Originally Bohai Huaifu County; one thousand households from Ping Intendant Office and Baoshan County were assigned.',
  ],
  s0457: ['Dingwu County.', 'Dingwu County.'],
  s0458: [
    'Originally Bohai Baoshan County land; carved out from Ping Prefecture Intendant Office and Rushui County households to establish it.',
    'Originally Bohai Baoshan County; Ping Intendant Office and Rushui County households founded it.',
  ],
  s0459: ['At first called Dinggong County.', 'Initially titled Dinggong County.'],
  s0460: ['Bin Prefecture, Huaihua Army, military commissioner.', 'Bin Prefecture (Huaihua Army), military commissioner.'],
  s0461: ['Originally Bohai fort.', 'Originally a Bohai fort.'],
  s0462: [
    'In Tonghe year 17 Wuran households were moved; a cishi was placed between the Yazi and Hunton rivers; 26 later it was raised.',
    'Tonghe year 17 relocated Wuran households; a cishi sat between Yazi and Hunton rivers; twenty-sixth note: later promoted.',
  ],
  s0463: [
    'Military affairs subordinate to the Huanglong Prefecture Deployment Office.',
    'Military affairs under Huanglong Prefecture Deployment Office.',
  ],
  s0464: ['27', '27'],
  s0465: ['Long Prefecture, Huanglong Prefecture.', 'Long Prefecture (Huanglong Prefecture).'],
  s0466: ['Originally Bohai Fuyu Prefecture.', 'It had been Bohai Fuyu Prefecture.'],
  s0467: [
    'Taizu, returning from pacifying Bohai, died here; a yellow dragon appeared, hence the rename.',
    'Taizu died here returning from conquering Bohai when a yellow dragon appeared, prompting the new name.',
  ],
  s0468: [
    'In Baoning year 7 army commander Yan Po rebelled and the prefecture was abolished.',
    'Baoning year 7: commander Yan Po rebelled and the prefecture was abolished.',
  ],
  s0469: [
    'In Kaitai year 9 the city was moved northeast; one thousand Han households from Zong and Tan prefectures restored it.',
    'Kaitai year 9 moved the city northeast; one thousand Han households from Zong and Tan prefectures refounded it.',
  ],
  s0470: ['Governing five prefectures and three counties:', 'Five prefectures, three counties:'],
  s0471: ['Huanglong County.', 'Huanglong County.'],
  s0472: [
    'Originally Bohai Changping County, with Fuli, Zuomu, and Sushen merged to establish it.',
    'Originally Bohai Changping County merged with Fuli, Zuomu, and Sushen.',
  ],
  s0473: ['Qianmin County.', 'Qianmin County.'],
  s0474: [
    'Originally Bohai Yongning County, with Fengshui and Fulu merged to establish it.',
    'Originally Bohai Yongning County merged with Fengshui and Fulu.',
  ],
  s0475: ['Yongping County.', 'Yongping County.'],
  s0476: ['Bohai established it.', 'Founded under Bohai.'],
  s0477: ['Yi Prefecture, observation commissioner.', 'Yi Prefecture (observation commissioner).'],
  s0478: ['Belonged to Huanglong Prefecture.', 'Subordinate to Huanglong Prefecture.'],
  s0479: ['Governing one county:', 'One county:'],
  s0480: ['Jingyuan County.', 'Jingyuan County.'],
  s0481: ['Anyuan Prefecture, Huaiyi Army, cishi.', 'Anyuan Prefecture (Huaiyi Army), cishi.'],
  s0482: ['Belonged to Huanglong Prefecture.', 'Subordinate to Huanglong Prefecture.'],
  s0483: ['Wei Prefecture, Wuning Army, cishi.', 'Wei Prefecture (Wuning Army), cishi.'],
  s0484: ['Belonged to Huanglong Prefecture.', 'Subordinate to Huanglong Prefecture.'],
  s0485: ['Qing Prefecture, Jianning Army, cishi.', 'Qing Prefecture (Jianning Army), cishi.'],
  s0486: ['Belonged to Huanglong Prefecture.', 'Subordinate to Huanglong Prefecture.'],
  s0487: ['Yong Prefecture, cishi.', 'Yong Prefecture (cishi).'],
  s0488: ['Belonged to Huanglong Prefecture.', 'Subordinate to Huanglong Prefecture.'],
  s0489: ['Hu Prefecture, Xingli Army, cishi.', 'Hu Prefecture (Xingli Army), cishi.'],
  s0490: ['Bohai established it.', 'Founded under Bohai.'],
  s0491: [
    'Military affairs subordinate to the Eastern Capital army command.',
    'Military affairs under Eastern Capital army command.',
  ],
  s0492: ['Governing one county:', 'One county:'],
  s0493: ['Changqing County.', 'Changqing County.'],
  s0494: ['Bo Prefecture, Qinghua Army, cishi.', 'Bo Prefecture (Qinghua Army), cishi.'],
  s0495: ['Bohai established it.', 'Founded under Bohai.'],
  s0496: [
    'Military affairs subordinate to the Eastern Capital army command.',
    'Military affairs under Eastern Capital army command.',
  ],
  s0497: ['Governing one county:', 'One county:'],
  s0498: ['Gongzhen County.', 'Gongzhen County.'],
  s0499: ['Bohai established it.', 'Founded under Bohai.'],
  s0500: ['Ying Prefecture, Zhangsheng Army, cishi.', 'Ying Prefecture (Zhangsheng Army), cishi.'],
};
