/** liaoshi 038 s0501–s0550 */
export const T = {
  s0501: ['Bohai established it.', 'Founded under Bohai.'],
  s0502: [
    'Military affairs subordinate to the Northern Jurchen Cavalry Command.',
    'Military affairs under Northern Jurchen Cavalry Command.',
  ],
  s0503: ['Governing one county:', 'One county:'],
  s0504: ['Yanqing County.', 'Yanqing County.'],
  s0505: ['Tong Prefecture, Guangli Army, cishi.', 'Tong Prefecture (Guangli Army), cishi.'],
  s0506: ['Bohai established it.', 'Founded under Bohai.'],
  s0507: [
    'Military affairs subordinate to the Northern Cavalry Command.',
    'Military affairs under the Northern Cavalry Command.',
  ],
  s0508: ['Governing one county:', 'One county:'],
  s0509: ['Ximu County.', 'Ximu County.'],
  s0510: [
    'Originally Han Wangping County land; Bohai made it Huashan County.',
    'Originally Han Wangping County; Bohai made Huashan County.',
  ],
  s0511: [
    'At first subordinate to the Eastern Capital; later came to belong here.',
    'First under the Eastern Capital; later transferred here.',
  ],
  s0512: ['Han Prefecture, cishi.', 'Han Prefecture (cishi).'],
  s0513: ['Bohai established it.', 'Founded under Bohai.'],
  s0514: [
    'Military affairs subordinate to the Southern Cavalry Command.',
    'Military affairs under the Southern Cavalry Command.',
  ],
  s0515: ['Suibin Prefecture, cishi.', 'Suibin Prefecture (cishi).'],
  s0516: ['Former Suibin state land.', 'Former Suibin state territory.'],
  s0517: ['Dingli Prefecture, cishi.', 'Dingli Prefecture (cishi).'],
  s0518: ['Former Yilou state land.', 'Former Yilou state territory.'],
  s0519: ['Tieli Prefecture, cishi.', 'Tieli Prefecture (cishi).'],
  s0520: ['Former Tieli state land.', 'Former Tieli state territory.'],
  s0521: ['Anding Prefecture.', 'Anding Prefecture.'],
  s0522: ['28', '28'],
  s0523: ['Changling Prefecture.', 'Changling Prefecture.'],
  s0524: ['Zhenhai Prefecture, defense commissioner.', 'Zhenhai Prefecture (defense commissioner).'],
  s0525: [
    'Military affairs subordinate to the Southern Jurchen Tanghe Office.',
    'Military affairs under Southern Jurchen Tanghe Office.',
  ],
  s0526: ['Governing one county:', 'One county:'],
  s0527: ['Pingnan County.', 'Pingnan County.'],
  s0528: ['Ji Prefecture, defense commissioner.', 'Ji Prefecture (defense commissioner).'],
  s0529: ['Shengzong built it and raised Yong\'an Army.', 'Shengzong founded it and raised Yong\'an Army.'],
  s0530: ['Dong Prefecture.', 'Dong Prefecture.'],
  s0531: ['Established with Bohai households.', 'Settled with Bohai households.'],
  s0532: ['Shang Prefecture.', 'Shang Prefecture.'],
  s0533: ['Established with Bohai households.', 'Settled with Bohai households.'],
  s0534: ['Ji Prefecture, Fuchang Army, cishi.', 'Ji Prefecture (Fuchang Army), cishi.'],
  s0535: ['Lu Prefecture, lower, cishi.', 'Lu Prefecture (lower rank), cishi.'],
  s0536: ['Bohai established it.', 'Founded under Bohai.'],
  s0537: ['Jing Prefecture, cishi.', 'Jing Prefecture (cishi).'],
  s0538: ['Yi Prefecture, Ningchang Army, military commissioner.', 'Yi Prefecture (Ningchang Army), military commissioner.'],
  s0539: [
    'In Taiping year 3 Princess Yue of the State was established with her dowry minister households.',
    'Taiping year 3: Princess Yue of the State received dowry-minister households.',
  ],
  s0540: [
    'At first called Qingyi Army; changed to Guangshun Army; subordinate to Shangjing.',
    'First Qingyi Army; renamed Guangshun Army; subordinate to Shangjing.',
  ],
  s0541: [
    'In Qingning year 7 Empress Xuanyi entered and the present name was changed.',
    'Qingning year 7: Empress Xuanyi\'s entry brought the present name.',
  ],
  s0542: ['Governing two counties:', 'Two counties:'],
  s0543: ['Ningchang County.', 'Ningchang County.'],
  s0544: ['Originally Pingyang County.', 'It was formerly Pingyang County.'],
  s0545: ['Shun\'an County.', 'Shun\'an County.'],
  s0546: ['Ying Prefecture, Changyong Army, cishi.', 'Ying Prefecture (Changyong Army), cishi.'],
  s0547: ['Shunhua Fort, Xiangyi Army, lower, cishi.', 'Shunhua Fort (Xiangyi Army, lower), cishi.'],
  s0548: ['In Kaitai year 3 established with Han households.', 'Kaitai year 3 founded with Han households.'],
  s0549: [
    'Military affairs subordinate to the Eastern Capital army command.',
    'Military affairs under Eastern Capital army command.',
  ],
  s0550: ['Ning Prefecture, observation commissioner.', 'Ning Prefecture (observation commissioner).'],
};
