/** liaoshi 038 s0551–s0608 */
export const T = {
  s0551: [
    'In Tonghe year 29 campaigning against Goryeo, it was established with surrendering Bohai households.',
    'Tonghe year 29 Goryeo campaign: founded with surrendering Bohai households.',
  ],
  s0552: [
    'Military affairs subordinate to the Eastern Capital army command.',
    'Military affairs under Eastern Capital army command.',
  ],
  s0553: ['Governing one county:', 'One county:'],
  s0554: ['Xin\'an County.', 'Xin\'an County.'],
  s0555: ['Yan Prefecture, Anguang Army, defense commissioner.', 'Yan Prefecture (Anguang Army, defense commissioner).'],
  s0556: ['Established with Han households.', 'Settled with Han households.'],
  s0557: [
    'At first cishi; later raised to an army.',
    'First a cishi prefecture; later raised to army status.',
  ],
  s0558: [
    'Military affairs belonged to the Eastern Capital army command.',
    'Military affairs under Eastern Capital army command.',
  ],
  s0559: ['Governing one county:', 'One county:'],
  s0560: ['Yifeng County.', 'Yifeng County.'],
  s0561: ['Lian Prefecture, Dechang Army, cishi.', 'Lian Prefecture (Dechang Army), cishi.'],
  s0562: ['Established with Han households.', 'Settled with Han households.'],
  s0563: [
    'Military affairs belonged to the Eastern Capital army command.',
    'Military affairs under Eastern Capital army command.',
  ],
  s0564: ['Governing one county:', 'One county:'],
  s0565: ['Anmin County.', 'Anmin County.'],
  s0566: ['Gui Prefecture, observation commissioner.', 'Gui Prefecture (observation commissioner).'],
  s0567: [
    'Taizu pacified Bohai and established it with surrendering households; later abolished.',
    'Taizu founded it with Bohai surrenderers; later abolished.',
  ],
  s0568: [
    'In Tonghe year 29 campaigning against Goryeo, it was restored with captured Bohai households.',
    'Tonghe year 29 Goryeo war restored it with captured Bohai households.',
  ],
  s0569: [
    'Military affairs belonged to the Southern Jurchen Tanghe Office.',
    'Military affairs under Southern Jurchen Tanghe Office.',
  ],
  s0570: ['Governing one county:', 'One county:'],
  s0571: ['Guisheng County.', 'Guisheng County.'],
  s0572: ['Su Prefecture, Anfu Army, military commissioner.', 'Su Prefecture (Anfu Army), military commissioner.'],
  s0573: [
    'Originally Goryeo Nansu; Xingzong established the prefecture.',
    'Originally Goryeo Nansu; Xingzong founded the prefecture.',
  ],
  s0574: [
    'Military affairs belonged to the Southern Jurchen Tanghe Office.',
    'Military affairs under Southern Jurchen Tanghe Office.',
  ],
  s0575: ['Governing two counties:', 'Two counties:'],
  s0576: ['Laisu County.', 'Laisu County.'],
  s0577: ['Huaihua County.', 'Huaihua County.'],
  s0578: ['Fu Prefecture, Huaide Army, military commissioner.', 'Fu Prefecture (Huaide Army), military commissioner.'],
  s0579: ['29 Xingzong established it.', 'Twenty-ninth note: Xingzong founded it.'],
  s0580: [
    'Military affairs belonged to the Southern Jurchen Tanghe Office.',
    'Military affairs under Southern Jurchen Tanghe Office.',
  ],
  s0581: ['Governing two counties:', 'Two counties:'],
  s0582: ['Yongning County.', 'Yongning County.'],
  s0583: ['Desheng County.', 'Desheng County.'],
  s0584: ['Su Prefecture, Xinling Army, cishi.', 'Su Prefecture (Xinling Army), cishi.'],
  s0585: [
    'In Chongxi year 10 prefecture people fled into the Jurchen; they were recovered and it was restored.',
    'Chongxi year 10: inhabitants fled to the Jurchen; recovery restored the prefecture.',
  ],
  s0586: [
    'Military affairs subordinate to the Northern Jurchen Cavalry Command.',
    'Military affairs under Northern Jurchen Cavalry Command.',
  ],
  s0587: ['Governing one county:', 'One county:'],
  s0588: ['Qing\'an County.', 'Qing\'an County.'],
  s0589: ['An Prefecture, cishi.', 'An Prefecture (cishi).'],
  s0590: [
    '30 Military affairs subordinate to the Northern Jurchen Cavalry Command.',
    'Thirtieth note: military affairs under Northern Jurchen Cavalry Command.',
  ],
  s0591: ['Rong Prefecture.', 'Rong Prefecture.'],
  s0592: ['Shuai Prefecture.', 'Shuai Prefecture.'],
  s0593: ['He Prefecture.', 'He Prefecture.'],
  s0594: ['Yuan Prefecture.', 'Yuan Prefecture.'],
  s0595: ['Bohai Prefecture.', 'Bohai Prefecture.'],
  s0596: ['Ningjiang Prefecture, Hunton Army, observation commissioner.', 'Ningjiang Prefecture (Hunton Army, observation commissioner).'],
  s0597: ['Established in the Qingning era.', 'Founded in the Qingning era.'],
  s0598: [
    'At first defense commissioner; later raised.',
    'First defense commissioner rank; later promoted.',
  ],
  s0599: [
    'Military affairs belonged to the Northeast Army Command.',
    'Military affairs under the Northeast Army Command.',
  ],
  s0600: ['Governing one county:', 'One county:'],
  s0601: ['Hunton County.', 'Hunton County.'],
  s0602: ['He Prefecture, Dehua Army.', 'He Prefecture (Dehua Army).'],
  s0603: ['An Arms Workshop was established.', 'An Arms Workshop was installed.'],
  s0604: ['Xiang Prefecture, Ruisheng Army, military commissioner.', 'Xiang Prefecture (Ruisheng Army), military commissioner.'],
  s0605: [
    'Xingzong established it with Tieli households.',
    'Xingzong founded it with Tieli households.',
  ],
  s0606: [
    'Military affairs subordinate to the Huanglong Prefecture Deployment Office.',
    'Military affairs under Huanglong Prefecture Deployment Office.',
  ],
  s0607: ['Governing one county:', 'One county:'],
  s0608: ['Huaide County.', 'Huaide County.'],
};
